### ISSUE TITLE
heat map colours are weird when analysing batch search results

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#100]
I've uploaded this list of targets, and when I click on the diseases I get redirected to an association page with funny looking table (and cells).
<img width="1019" alt="screen shot 2017-04-03 at 10 43 00" src="https://cloud.githubusercontent.com/assets/6472381/24604295/27027a72-185c-11e7-93c6-b37bf26de8f8.png">

Also I've noticed the blue colour when I'm on the association table is light blue but the score is 1:
<img width="902" alt="screen shot 2017-04-03 at 10 52 07" src="https://cloud.githubusercontent.com/assets/6472381/24604360/63ec099e-185c-11e7-84a8-1506ecc3f881.png">

Would this be a bit confusing for users?

ADCY7
ATG16L1
CARD9
CD6
ERAP2
FCGR2A
FUT2
ICAM1
IFIH1
IL10
IL18RAP
IL23R
IL2RA
ITGA4
ITGAL
ITGB8
MST1
NOD2
NXPE1
PLCG2
PTPN22
SLAMF8
SMAD3
SP140
TNFSF8
TYK2

**Comment by emepyc** [comment]
Thanks for the heads up. Reloading displays the data correctly, I'm looking at this now

**Comment by emepyc** [comment]
This should be fixed now (version 3.0.7)
