### ISSUE TITLE
Change "Analyze targets" to "Analyse targets" in batch search button 

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#108]
https://www.targetvalidation.org/batch-search

![screen shot 2017-04-11 at 12 31 26](https://cloud.githubusercontent.com/assets/20280139/24907199/221e74f4-1eb3-11e7-985d-b7fe8576ad29.png)

I think we use UK spelling (analyse) throughout.

**Comment by emepyc** [comment]
Fixed.
