### ISSUE TITLE
use same icon for pvalue explanation as for score

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#109]
We use a question mark icon for the link to the score FAQ:

![screen shot 2017-04-11 at 13 03 14](https://cloud.githubusercontent.com/assets/20280139/24908314/71781e70-1eb7-11e7-8944-47cd031bd199.png)

But for the explanation of the pvalue we use the [i] icon:
![screen shot 2017-04-11 at 12 27 00](https://cloud.githubusercontent.com/assets/20280139/24908335/8e0f55ee-1eb7-11e7-852d-b0e6192dd94a.png)

We should use the same for both (presumably the questionmark?)

**Comment by emepyc** [comment]
We should use the "i" with the tooltip in the score as well

**Comment by nikiforosk** [comment]
I think @peatroot is planning to add a tooltip icon for the tissue expression filter which should be an "i" as well then.

**Comment by emepyc** [comment]
it is
