### ISSUE TITLE
Ensembl IDs in "Your target list" (on associations page) 

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#112]
Going from [the summary page of my list](https://www.targetvalidation.org/summary?targets=172057,73756,12779,142192,137642,137845,87085,138378,105397,160856,168229,95303,280151,108219,198369,105401,134882,197272,181915,178623,107968,133195,171522,116288,169508,143365,95110,109787,179344,153064,108094,116833,151151,111537,114859,169220) to the [filtered associations page for Crohn's disease](https://www.targetvalidation.org/disease/EFO_0000384/associations?targets=168229,95303,198369,142192,160856,280151,181915,151151,171522,73756,114859,178623,87085,105401,137845,12779,143365,108219,137642,111537,109787,116833,116288,153064,169508,172057,133195,134882,108094,179344,197272,107968,138378,105397,169220,95110).

We use Ensembl IDs for target names:
![screen shot 2017-04-11 at 13 13 46](https://cloud.githubusercontent.com/assets/20280139/24908746/222b6e06-1eb9-11e7-94f9-b6776cd5d681.png)

I find this odd because we use HGNC symbols for target names in all other UI strings (including the associations table on the same page).

Also in this particular flow, the names on my list were mapped to HGNC symbols in https://www.targetvalidation.org/batch-search so it's strange to see Ensembl IDs now.

**Comment by andrewhercules** [comment]
Issue closed as "Your target list" on disease associations page shows HGNC symbols - see below for an example.

![screen shot 2018-06-25 at 09 47 46](https://user-images.githubusercontent.com/7490258/41840135-e62283c8-785c-11e8-9063-70ea60bc39f0.png)
