### ISSUE TITLE
issues with the "Picasso panel"

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#113]
I have several reservations about the "Picasso panel" (PP).

** Not well suited to the main of objectives of the search results page**

The main objective of the search results page is to allow people to:

a) Preview the genes or diseases that match their search query: So if someone searches for "BRAF" we want them to be able to see that there are several HGNC symbols (and perhaps even disease names) matching "BRAF" and select the target/disease they are interested in.

Effectively in this page we are asking them _What do you mean by "BRAF"?_

The autocomplete suggestions are effectively a condensed version of the search results page. In the search results page we offer more matches than in the autocomplete suggestions.

b) Once they have selected an HGNC symbol, we want them to go to the associations page for this target.

After the introduction of the PP, it's more difficult to meet these objectives because:

a) Most of the search results are now hidden (especially when you view it on a laptop screen). 

Compare version 3.0 (https://www.targetvalidation.org/search?src=q:BRAF):
<img width="1266" alt="braf-search-beta-screen shot 2017-03-27 at 14 45 58" src="https://cloud.githubusercontent.com/assets/20280139/24909360/7f10a2a6-1ebb-11e7-8460-117c034fc9d3.png">

with the results that were visible in the previous version:
<img width="1266" alt="braf-search-public-screen shot 2017-03-27 at 14 46 14" src="https://cloud.githubusercontent.com/assets/20280139/24909401/a5453d1a-1ebb-11e7-9a27-b87cc434a14d.png">

So instead of asking  _What do you mean by "BRAF"?_ we are now showing more information about the first hit and hiding the additional matches below the fold.

I think this is problematic as people may not realise that there are other entities matching their query. Also this design may lead them to believe that this is the page for BRAF (some people in earlier user testing searched for a target, looked at the diseases in the search results and thought that these were the associated diseases for the target, and vice versa).

b) It's now harder to go to the associations page.

To go to the [associations page for BRAF](https://www.targetvalidation.org/target/ENSG00000157764/associations) one needs to click on the link at the top of the PP. This is much harder to guess in the new design because of the introduction of additional links and information. 

Miguel suggested hyperlinking "501 diseases associated" too. This may be useful but notice how far away "501 diseases associated" is from the "top associated diseases". 

I'm also not sure how we selected the additional information:

- Phase 4 drugs: People will be asking which are these drugs. There is no link to this (and it's actually quite hard to find in the Target Profile page).

- Biotype / UniProt accessions: Is this so important? There is other information in the target profile page that people have explicitly asked for in a Summary view but I don't remember much demand for those particular two pieces of information.

**Comment by nikiforosk** [comment]
I think the original motivation was to use the space on the side to provide additional information on the first hit, like google does:
https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=piccasso
https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=queen

But I don't think that this information should come at the expense of the 2 objectives for the search page that I stated above. 

I recommend reverting to the previous version for the search results page.

We can investigate the design of a Summary page for a target where we pull the critical information from the target profile page one level up (but after the search results).

**Comment by LucaFumis** [comment]
I had a quick go at a mock in the browser the other day;
Did you mean something like this Niki?

![screen shot 2017-07-04 at 17 00 34](https://user-images.githubusercontent.com/8592363/27905626-69a20ae8-6238-11e7-9cf2-9f6bd3243c5e.png)

![screen shot 2017-07-04 at 17 14 41](https://user-images.githubusercontent.com/8592363/27905637-78fa863c-6238-11e7-8201-a22328d22c5a.png)

**Comment by nikiforosk** [comment]
I think we should keep showing BRAF at the top of the list, and any additional info about BRAF on the side. My first thought when I looked at the mockup was that RAF1 is now the top hit (and BRAF something less relevant, a bit like an advertisement on the side).

**Comment by LucaFumis** [comment]
Thanks for the feedback Niki - good points there

**Comment by emepyc** [comment]
Yes, I agree with Niki. The list should show the top result as well and additional info in the panel. On small screens google place the panel on top and then the results (list), we may prefer to hide the panel altogether?

**Comment by LucaFumis** [comment]
I tried the layout changes last week. 
Have a preview, but doesn't seem to be loading data at the moment (unrelated to the code for this issue): https://picassopanel--private-livers-86388.netlify.com/

**Comment by LucaFumis** [comment]
The preview is now working so the updated version can be reviewed:
https://picassopanel--paratrooper-antelope-70721.netlify.com/search?src=q:braf
https://picassopanel--paratrooper-antelope-70721.netlify.com/search?src=q:asthma
The panel is hidden on smaller screens.

**Comment by emepyc** [comment]
I just noticed that `Orto:` field in the list of results. Probably following `match_from_ortholog`.

**Comment by LucaFumis** [comment]
Thanks Miguel, well spotted - that's fixed now.
Had a quick review with Niki the other day: overall the new layout works better; there are however still some doubts about content (e.g. why only phase 4 drugs? ), which ideally it should give a quick overview of info we have in the profile page.

**Comment by elipapa** [comment]
while the content can be reviewed at a later date, the new layout does work better.
Closing for now.
