### ISSUE TITLE
3 digit number in bar chart has little padding

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#115]
When the number in the bar chart that shows how many targets from a list are associated with a disease (or appear in a pathway) has more than two digits, it takes over most of the white circle (and therefore looks a bit "squashed". 

Compare "157" to "77" below from [this example](https://www.targetvalidation.org/summary?targets=169194,172057,113448,133048,168229,149451,113580,73756,169252,12779,111424,113525,187258,175497,173198,146070,95303,91181,171195,90376,196639,168539,43591,133019,213047,150594,184588,170214,211891,188778,170425,65989,183134,160716,128271,101204,171873,186009,120907,172572,184160,163485,105650,105675,152270,282608,274286,73605,113161,167914,145777,77238,113721,157404,134853,68078,228716,137033,134376,115602,128536,115604,169245,137507,123411,174125,164756,107485,179344,166949,169248,185664,134987,254470,138755,161405,170185,119922,237541,232810,163564,271503,160712,131437,182393,112115,69667,100385,135114,183709,38532,113522,96093,186207,197110,109458,136244,185745,102524,132170,104783,134321,124256,197375,119917,226025,180871,136160,172156,151617,184557,136634,163464,205189,125347,174697,132359,107201,72041,7171,177663,171044,104951,108691,134215,134184,105329,79308,185532,128383,185338,162654,169429,178568,197536,138646,204671,115267,127318,142166,131203,102468,168062,136869,10030,89692,134259,159110,177409,187608,146192,198673,134489,113520,171608,164400,49130):
<img width="1156" alt="barchart-3digits-screen shot 2017-04-18 at 15 07 53" src="https://cloud.githubusercontent.com/assets/20280139/25137284/3c819a28-244f-11e7-86a1-34fc5ef7de70.png">

We may need to increase the horizontal padding for numbers with more than 2 digits (which may change the white circle to an oval).

**Comment by peatroot** [comment]
This is a valid issue. However, since we support a maximum of 200 targets in the batch search, if the number of associated targets requires three digits, the first will be `1`, which visibly fits in the above screenshot. We can reopen this issue if the maximum target count is increased above 200.
