### ISSUE TITLE
Association with no supporting evidence: section isn't greyed out

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#116]
ADAM19 - asthma
https://www.targetvalidation.org/evidence/ENSG00000135074/EFO_0000270

There is no evidence to support this association. However, the text mining section does not look greyed out (and the "No data available" message is missing):

![screencapture-targetvalidation-org-evidence-ensg00000135074-efo_0000270-1492608246519](https://cloud.githubusercontent.com/assets/20280139/25182299/0f9c337a-250c-11e7-8c3f-bdac6fc14182.png)

**Comment by nikiforosk** [comment]
ADAM19 - asthma
https://www.targetvalidation.org/evidence/ENSG00000135074/EFO_0000270

Also the flower is not showing at all. I'd expect all petals to look greyed out, like we do in associations like this:
https://www.targetvalidation.org/evidence/ENSG00000148408/EFO_0000270
<img width="980" alt="screen shot 2017-04-19 at 14 24 49" src="https://cloud.githubusercontent.com/assets/20280139/25182375/4cca892c-250c-11e7-89e7-ace837064fd6.png">
So all petals would look like Mouse and Genetics.

**Comment by emepyc** [comment]
Should be fixed now in beta

**Comment by MichaelaEBI** [comment]
I found another association that looks similar to what has been described above - sections are not greyed out and no flower: http://www.targetvalidation.org/evidence/ENSG00000167711/Orphanet_1478

It says this in the console when the page is loading: TypeError: t.body.data[0] is undefined

**Comment by MichaelaEBI** [comment]
I looked into this a bit more and @ckongEbi and I agree that the summary page for associations without any evidence should show the following:
* A greyed out empty flower
* All sections greyed out

This will mostly be relevant to associations that had text mining evidence only and tidying up the text mining 'removed' the association. Here are a few more examples of associations without any evidence:
http://www.targetvalidation.org/evidence/ENSG00000167711/Orphanet_271853
http://www.targetvalidation.org/evidence/ENSG00000167711/Orphanet_1478
http://www.targetvalidation.org/evidence/ENSG00000167711/Orphanet_1479
http://www.targetvalidation.org/evidence/ENSG00000167711/Orphanet_1480

**Comment by ckongEbi** [comment]
looping in @LucaFumis @peatroot @andrewhercules

**Comment by LucaFumis** [comment]
The code always assume that `data` will contain something: we can put a check there to not trigger an error.
But how do you get to one of these pages? Looking at association page for, say, the given target, I can find the disease in the list...

**Comment by peatroot** [comment]
There is no association between this particular target and disease pair, so a user could never get to this page from within the `webapp` except by manually constructing the URL string for the evidence page. Is that what you did, @MichaelaEBI?

**Comment by MichaelaEBI** [comment]
Sorry for the delay in responding - I followed a link that was saved in the Text Mining False Positive spreadsheet. I thought it possible that users might save a link to go back to later and then they could land on an association that no longer exists. I don't know how often that would happen.

**Comment by andrewhercules** [comment]
Given that this page isn't accessible unless the user directly accesses it via a saved link, we could implement a small change to make it clear that the Platform does not have data supporting the association. For example, we could we add some front-end logic that if `data` is empty, we render a different view with a message providing links to the target and disease associations page. 

@LucaFumis, I'm flagging this as a possible ticket for a mini-release. What do you think?

**Comment by LucaFumis** [comment]
That sounds good @andrewhercules.

**Comment by LucaFumis** [comment]
I fixed the breaking flower/sections when there is no evidence data.
On the evidence page we still have inconsistencies when we have evidence with score 0 - while this is addressed in the associations pages (heatmap), it is still outstanding here (will need to update the flower). So perhaps best to fix this first, then have a different view for when we have no evidence data as reported here.
Marking as fixed for now, but can review.
