### ISSUE TITLE
link to opentargets/github

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#117]
@deniseOme commented on [Wed Mar 08 2017](https://github.com/opentargets/platform_issues_triage/issues/18)

One user at a workshop suggested having a link to our github.

Perhaps from the API menu?!?!?

![screen shot 2017-03-08 at 17 22 28](https://cloud.githubusercontent.com/assets/6472381/23715236/d7982870-0423-11e7-877d-f3f54a7efec3.png)

---

@nikiforosk commented on [Thu Mar 09 2017](https://github.com/opentargets/platform_issues_triage/issues/18#issuecomment-285305839)

Maybe this Menu should be called "For developers" (and perhaps include the Downloads)?

See e.g. the ubuntu site: 
https://developer.ubuntu.com/en/?_ga=1.221482712.1161247147.1489052972

---

@deniseOme commented on [Thu Mar 23 2017](https://github.com/opentargets/platform_issues_triage/issues/18#issuecomment-288690702)

We may revisit this later...Perhaps get some use cases, and the advantages of having the link (just to say we are open? We want to expose our codebase? If the latter, there may be other ways to do so.

---

@elipapa commented on [Mon Apr 24 2017](https://github.com/opentargets/platform_issues_triage/issues/18#issuecomment-296710058)

we'll include it in the footer.

**Comment by emepyc** [comment]
A new twitter icon has been included in the footer linking to the opentargets github organisation page.
Deployed in beta.
