### ISSUE TITLE
download the top 100 paper from the text mining results

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#118]
@elipapa commented on [Wed Feb 22 2017](https://github.com/opentargets/platform_issues_triage/issues/14)

these should be ranked by some measure of significance. EuropePMC does provide an internal score we could use. 

---

@deniseOme commented on [Wed Feb 22 2017](https://github.com/opentargets/platform_issues_triage/issues/14#issuecomment-281653021)

The user would appreciate it if we could  add back the download button. They've suggested to add a maximum number exported to make it less technically challenging. They are not sure what that number would be.

---

@deniseOme commented on [Wed Feb 22 2017](https://github.com/opentargets/platform_issues_triage/issues/14#issuecomment-281653374)

Latest communication with the user, the REST API endpoint (https://targetvalidation.org/api/latest/public/evidence/filter?target=ENSG00000182578&disease=EFO_0000249&datatype=literature&format=tab) was provided as an alternative for the time being.

---

@deniseOme commented on [Wed Feb 22 2017](https://github.com/opentargets/platform_issues_triage/issues/14#issuecomment-281667420)

The original user request was: "is there a way for me to pull the articles from your Europe PMC Text mining for a particular gene/target combination? For example via a static web link or the open targets API".

**Comment by emepyc** [comment]
The download button has been re-included in the text mining evidence table.
There is a limit of 200 papers and this is stated in the button tooltip.
The download follows whatever sorting you have in the table just before downloading
