### ISSUE TITLE
Page header background not grey?

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#120]
The background of the page header (i.e the area below the masthead) used to be grey:
![01a-pde4d-associations-bubbles-02](https://cloud.githubusercontent.com/assets/20280139/25566425/4f368e32-2dd0-11e7-8a40-14af469896c5.png)

![evidence-pde4d-asthma](https://cloud.githubusercontent.com/assets/20280139/25566427/72556b04-2dd0-11e7-9bc0-18fb274f23c2.png)

Today I noticed that it is white (like the rest of the page):
![app-associations-tanervous-1493545809885](https://cloud.githubusercontent.com/assets/20280139/25566444/95af2716-2dd0-11e7-84c6-c1ebb651b5cd.png)

![app-add-1493546045150](https://cloud.githubusercontent.com/assets/20280139/25566446/9babc142-2dd0-11e7-81e9-39f186c46493.png)

When did we make this chance? Where did we document the rationale for it?

**Comment by LucaFumis** [comment]
The grey background was removed a few months back. Main reasons, in short:
 - It required all pages to follow a specific structure
 - the height of the bar was inconsistent across pages (depending on content), which looked untidy while not particularly adding anything.
Not documented.

**Comment by nikiforosk** [comment]
We need to discuss these changes before they are implemented. I remember some good reasons why we wanted the header to look separate from the rest of the page (although this doesn't need to be a grey background, it could be a line as in Amazon). 

We also need to be documenting these changes. At the moment it's very hard to keep track of what's been changing in the UI.

**Comment by emepyc** [comment]
Sorry Niki, but we can't document every minor change in the UI.
Btw, can you point me to the document where the original design was discussed?

**Comment by nikiforosk** [comment]
You (as developers, plural) have the responsibility to discuss such changes with me. I did this with Luca when we decided to implement this change (although you're right to say that this hasn't been documented). There are a lot of "minor" changes going on without discussion and documentation and this is becoming borderline unprofessional.

Moving forward, I think you should commit to better documentation. I also think as a lead front end developer your responsibility (singular) is to ensure that this happens. Telling me that you can't document and share what you're working on is not acceptable.

**Comment by emepyc** [comment]
Niki,
I think you have crossed several lines here and I'm not going to play this game.
We should clarify several things before this gets worse, but a public issue tracker is definitely not the place for it.
