### ISSUE TITLE
update /scoring page to reflect different factors affecting score calculation at the evidence level (e.g. EVA)

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#121]
@iandunham @ckongEbi @emepyc: following the inclusion of trinucleotide expansion and consequent comments at the Alzheimer's RUK workshop regarding HTT and HD, it became clearer that https://www.targetvalidation.org/scoring is not 100% accurate regarding S = f x C x s applying to other data types than GWAS.

@ckong will compile this information on github so that we can update the help docs on the Platform in due course.

**Comment by emepyc** [comment]
Do we want to have this in 3.1? (ie, the next data release?)

**Comment by ckongEbi** [comment]
This is the wiki on scoring I am populating gradually for different data sources, feel free to adapt for use on the https://www.targetvalidation.org/scoring page

https://github.com/opentargets/data-providers-docs/wiki/Data-(Evidence-Strings)-Generation-Process

**Comment by emepyc** [comment]
@deniseOme, @ckongEbi, do we have enough information to update these docs?

**Comment by deniseOme** [comment]
I do not have extra info on the new data sources i.e. Genomics England and PheWAS. Waiting to hear from @gkos-bio @PriyankaW @elipapa @apierleoni et al as per the email below:

![screen shot 2017-07-14 at 16 05 29](https://user-images.githubusercontent.com/6472381/28217798-4bb6a878-68ae-11e7-9e1b-6bea21bf4cee.png)

**Comment by elipapa** [comment]
for phewas you can use something similar to GWAS. For instance _"PheWas Catalog (normalised p-value and normalised sample size"_

The plan is to separate scoring out of mrTarget and make it publicly available: https://github.com/opentargets/data_pipeline/issues/42

**Comment by emepyc** [comment]
Do we still need to do something with this? if not we will close it

**Comment by andrewhercules** [comment]
Issue moved to [opentargets/docs.targetvalidation.org #3](https://github.com/opentargets/docs.targetvalidation.org/issues/3) via [**ZenHub**](https://www.zenhub.com/)
