### ISSUE TITLE
datatype or data type?

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#122]
Could we separate the two words here (Facet 'Filter by datatype) and elsewhere when appropriate?

https://www.targetvalidation.org/target/ENSG00000056972/associations?fcts=therapeutic_area:efo_0000701&view=t:table

![screen shot 2017-05-08 at 10 28 01](https://cloud.githubusercontent.com/assets/6472381/25799082/98d0bf2a-33db-11e7-9d90-fc02a3f0e22e.png)

**Comment by emepyc** [comment]
Fixed in beta now.
I haven't found any other instance, but if there are more, please feel free to reopen and comment

**Comment by deniseOme** [comment]
The results of the batch search show Datatypes (under Diseases associated) e.g.

![screen shot 2017-05-17 at 10 59 24](https://cloud.githubusercontent.com/assets/6472381/26148891/1a279fb0-3af0-11e7-84b8-9cb89d0aa194.png)

**Comment by emepyc** [comment]
this was already fixed
