### ISSUE TITLE
Publication column under Somatic mutations: empty rows

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#123]
Publication seems not to be available for some target-disease associations based on somatic mutations data type e.g.:

https://www.targetvalidation.org/evidence/ENSG00000139618/EFO_0000305?view=sec:somatic_mutations

and

https://www.targetvalidation.org/evidence/ENSG00000105810/EFO_0000305?view=sec:somatic_mutations

I wonder why that is the case? When clicking on the link to Cancer Gene Census there seems to be a list of papers (without delving deeper in their data or ours):

http://cancer.sanger.ac.uk/cosmic/gene/analysis?ln=BRCA2&mut=deletion_inframe

http://cancer.sanger.ac.uk/cosmic/gene/analysis?ln=CDK6&mut=substitution_missense

At any rate, wouldn't it be worth populating that row with either 'N.A.' or something else under the Publications column (rather than an empty row)?

**Comment by emepyc** [comment]
N/A has been added now to that cells. If there are publications that are not reaching the webapp, please feel free to move this issue to the data_pipeline repo
