### ISSUE TITLE
Error: Unexpected token < in JSON at position 4

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#124]
The Atlas Expression (baseline) widget here

https://www.targetvalidation.org/target/ENSG00000105810

does not load and give an error message.

GTEx is fine.

![screen shot 2017-05-08 at 13 24 12](https://cloud.githubusercontent.com/assets/6472381/25804085/f21904c8-33f1-11e7-9d6c-ee8b50ba0f18.png)

**Comment by gkos-bio** [comment]
On chrome (Windows 7), there is a spinning wheel and that's all.
Would be great if the tabs were displayed first so that a user can always go to GTEx if the Expression Atlas widget fails.

**Comment by deniseOme** [comment]
Using Google on Mac, I see the error above and can open the GTEx tab.
In Firefox and Safari (Mac) I see the spinning wheel, and no way to get to the GTEx tab.

The widget is working fine in Ensembl (google):
http://www.ensembl.org/Homo_sapiens/Gene/ExpressionAtlas?db=core;g=ENSG00000175164;r=9:133250401-133275214

![screen shot 2017-05-08 at 14 53 43](https://cloud.githubusercontent.com/assets/6472381/25807282/30b4d174-33fe-11e7-91de-42a9996865af.png)

**Comment by emepyc** [comment]
I've just contacted them. It looks they are changing the bundles (releasing a new version). Maybe Ensembl is caching the prev version.
Anyway, the widget seems to be unstable at the moment.
I'll follow up with them

**Comment by emepyc** [comment]
This should be fixed in beta and production
