### ISSUE TITLE
ABO target profile: UniProt info

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#125]
On https://www.targetvalidation.org/target/ENSG00000175164, there is no info re. 

Subunit:
Subcellular location:
UniProt Keywords:

However subcellular location and keywords seem to be available in UniProt:
http://www.uniprot.org/uniprot/P16442#subcellular_location

Same behaviour in beta:
https://beta.opentargets.io/target/ENSG00000175164

**Comment by emepyc** [comment]
Probably a data issue: we may not be in sync with latest version of uniprot?
@ckongEbi can you please take a look? It is probably fine to close this issue if that is the case

**Comment by ckongEbi** [comment]
we can see this information in **17.04_uniprot-data/uniprot-gene/P16442** 
![screen shot 2017-05-09 at 21 32 51](https://cloud.githubusercontent.com/assets/6169985/25871493/94349c14-34ff-11e7-9b23-9b1f62dfdec2.png)

But those section are empty in 17.04_gene-data/genedata/ENSG00000175164
![screen shot 2017-05-09 at 21 33 56](https://cloud.githubusercontent.com/assets/6169985/25871516/ae9bd752-34ff-11e7-9dcb-c063ada683e0.png)

suggesting this happens during gene-merging step @apierleoni ? This is the same in 17.02 data, @emepyc can we move this to "data_pipeline" repo

**Comment by emepyc** [comment]
Issue moved to [opentargets/data_pipeline #120](https://github.com/opentargets/data_pipeline/issues/120) via [**ZenHub**](https://www.zenhub.com/)
