### ISSUE TITLE
Overlapping data sources leading to duplication of data in the UI

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#126]
Is it correct to display the same variant twice (as the evidence comes from different sources, i.e. UniProt and ClinVar in the example below:

https://beta.opentargets.io/evidence/ENSG00000102081/Orphanet_908?view=sec:genetic_associations

This is potentially confusing for users.

**Comment by emepyc** [comment]
Issue moved to [opentargets/platform_issues_triage #31](https://github.com/opentargets/platform_issues_triage/issues/31) via [**ZenHub**](https://www.zenhub.com/)

**Comment by emepyc** [comment]
This is the consequence of having overlapping data sources. I don't think we can do much about this.
Even if we accept this as an issue, it would be data related, since merging these evidence should be done at the data level.
