### ISSUE TITLE
Bug in converting the associations to tree structure when only 1 association

### ISSUE THREAD

**Issue by emepyc** [opentargets/webapp#128]
Possibly in flat2tree (api module). It looks like when there is only 1 association, the tree construction is failing.
example:
http://targetvalidation.org/target/ENSG00000143631/associations?fcts=datasources:eva&view=t:bubbles

When loading the table it works fine, bubbles view and tree view don't display.

**Comment by andrewhercules** [comment]
Issue closed as bug has been resolved - see https://www.targetvalidation.org/target/ENSG00000143631/associations?fcts=therapeutic_area:EFO_0000319&view=t:bubbles and https://www.targetvalidation.org/target/ENSG00000143631/associations?fcts=therapeutic_area:EFO_0000319&view=t:tree for examples where there is only 1 association.
