### ISSUE TITLE
better title for batch search result page

### ISSUE THREAD

**Issue by emepyc** [opentargets/webapp#129]
Currently the title is just "Open Targets Platform". Something like "Open Targets results for X targets" would be more useful

**Comment by LucaFumis** [comment]
It might be missing the `view-title` directive?
Generally added to a page main header, e.g. `<h3 view-title class="ng-binding">Evidence for BRAF in astrocytoma</h3>` (It automatically appends the ` - Open Targets Platform` at the end).
It's a bit buggy in Chrome though, and not always work...

**Comment by emepyc** [comment]
Thanks Luca, I'm not sure the directive is used in that page
