### ISSUE TITLE
clicking on the first target in the picasso page: weird behaviour in production and beta

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#131]
At the dundee workshop using Production, when clicking on the gene in the picasso panel, we were taken to the home page rather than the evidence page.

This is fixed in beta but the example below shows a weird behaviour:

https://beta.opentargets.io/evidence/ENSG00000146648/EFO_0005288

There is TM data but the TM petal in the flower is not coloured.

other examples:
https://beta.opentargets.io/evidence/ENSG00000142192/EFO_0000249

https://beta.opentargets.io/evidence/ENSG00000138193/EFO_0005547

**Comment by emepyc** [comment]
As you say the issue with the picasso panel is fixed in beta.
The other issues you mention about the evidence page are not very meaningful right now, since data is still being loaded in ES and inconsistent behaviour is expected.

**Comment by emepyc** [comment]
This seems to be working as expected now both in beta and production
