### ISSUE TITLE
CD86 profile page in IE11

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#132]
At the Dundee workshop, many were using IE11.

This is one bug they've found: CD86 IE 11: interaction path did not show up.
@gkos-bio just checked this again with his IE and did replicate the issue.

It works fine in google chrome and firefox:

![screen shot 2017-05-12 at 16 23 04](https://cloud.githubusercontent.com/assets/6472381/26004919/509113ac-372f-11e7-90ad-14673b4b8e75.png)

**Comment by emepyc** [comment]
This was already fixed. I have just checked again and the interactions viewer seems to work ok in IE11
