### ISSUE TITLE
suggested matches in batch search

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#134]
When uploading a list into the batch search, one gene gets a suggested match, which does not seem to be different at all. They seem to be the same i.e. ptgs2 --> PTGS2.

[target_list.txt](https://github.com/opentargets/webapp/files/1042088/target_list.txt)
![screen shot 2017-05-31 at 16 32 56](https://cloud.githubusercontent.com/assets/6472381/26640221/0c134a0c-461f-11e7-903b-c999ea7717fa.png)

**Comment by emepyc** [comment]
Issue moved to [opentargets/rest_api #74](https://github.com/opentargets/rest_api/issues/74) via [**ZenHub**](https://www.zenhub.com/)
