### ISSUE TITLE
Outreach page revamp

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#138]
The above is getting out of control (and not pleasing to the eye) with the many events over the last months.

It would be nice to revamp this whenever possible.

Do we need to list all past events? Or have "show more" similar to this:

http://www.earlham.ac.uk/scientific-training
![screen shot 2017-06-02 at 16 26 24](https://cloud.githubusercontent.com/assets/6472381/26732647/2fbfe982-47b0-11e7-9630-bc56938495ed.png)

Perhaps include one quote from a participant, similar to:

![screen shot 2017-06-02 at 16 27 06](https://cloud.githubusercontent.com/assets/6472381/26732676/51835d56-47b0-11e7-9021-de58f72dc108.png)

Or/and images:
http://www.earlham.ac.uk/past-events

Pluse include the GIF animations below:

http://imgur.com/a/LKDhp
http://imgur.com/a/JIDCP

?????

**Comment by deniseOme** [comment]
We have a new set of slides for the 'Let's get started with the Platform', attached here as pdf.

I have the original gifs for the tour de force of Platform and Batch search. These will get updated eventually. They are too big to be uploaded here though.

[OpenTargets_Platform_Let'sGetStarted_DGH_ID_DCS.pdf](https://github.com/opentargets/webapp/files/1224716/OpenTargets_Platform_Let.sGetStarted_DGH_ID_DCS.pdf)

**Comment by deniseOme** [comment]
Please include the video (https://vimeo.com/233638392) when possible.
It will be part of a series entitled How to.

This is How to find diseases with Open Targets.

**Comment by deniseOme** [comment]
@emepyc has improved some of this e.g. added "show more" for past events.

<img width="143" alt="screen shot 2018-01-31 at 20 27 07" src="https://user-images.githubusercontent.com/6472381/35645820-1acbcefe-06c5-11e8-9b0b-743827d0761e.png">
 
Now that we have a handful of videos/animations, can we remove the slides and add a text/link to our youtube?

e.g. Watch out tutorials (linking to https://www.youtube.com/channel/UCLMrondxbT0DIGx5nGOSYOQ/featured)

**Comment by deniseOme** [comment]
@ElaineMcA @andrewhercules @LucaFumis @iandunham 

I'd like to get back to this idea of revamping the Outreach page, hence reopening the issue here. The future page does not need to look too fancy (perhaps an image of the entire team in a party environment, similar to the one in opentargets.org; plus other images).

A list of upcoming/past events only is good but it can be off-putting.

We can also include "Talks" in general (not only in training capacity) by other team members similar to this:

https://md.catapult.org.uk/events/

For example, Ian at Genomics England tomorrow, Phillipe at Festival of Genomics and Elixir events, etc). This will be good for increasing visibility.

This page is fed from https://github.com/opentargets/live-files/blob/gh-pages/outreach.json
and I maintain this so that other resources e.g. Elixir can point to us.

Can I suggest we look into this after the summer? Perhaps September?

**Comment by andrewhercules** [comment]
Here's an initial idea I had for rebranding the static pages in a consistent manner: **https://nascqi.axshare.com**

The images and icons are all placeholders and can be switched later. Also, I realise that it uses a lot of the OT blue and so will work to amend the colours at a later date. But at this point, I wanted to focus on a new page layout and flow. 

What do you think @deniseOme?

**Comment by deniseOme** [comment]
Thanks @andrew a lot for this. At a first glance, it looks great! The timeline is awesome.

These are my specific and detailed thoughts on the your first mock up of our “About” page so far:
1) Ecosystem
We have been using this word in meetings internally but I can’t seem to find the word elsewhere, e.g. in opentargets.org. I can see resources though. 
What do we mean by ‘ecosystem’? Apps? Tools? Portals? Resources? Portfolio?

Is Open Targets, the consortium, an ecosystem?

2) What is the rationale behind the order of the those tabs? Shall we go alphabetically?
Screen Shot 2018-08-07 at 12.19.07

3) I’d avoid using the abbreviation OT as in ‘OT Genetics’.

4) Can we use real images from training sessions instead of the stock ones? Or perhaps use vectors?

5) I’d have shortened some of the sub-headings e.g. ‘Want to keep up to date with the latest’, ‘Watch a short video…’

6) I’d have an extra space between the social media icons and the newsletter title (i.e. Want to keep up to date with the latest…).

<img width="581" alt="screen shot 2018-08-07 at 12 22 37" src="https://user-images.githubusercontent.com/6472381/43773073-67323480-9a3c-11e8-9c82-12390dacdb15.png">

When I first looked at the page, I could only see the “Subscribe” button. So extra space may dilute the busyness of that part of the page.

Shout if you want me to draft some text for some of the categories.

**Comment by deniseOme** [comment]
As per the Outreach page: it looks great. Layout with a hero image and the blue box in line with the About mock up is a sensible idea.

Some specifics for when the time is right to tackle them:

1) Hero image
I’d suggest trying to have a picture from a real training session of ours. If not possible, get a pic from the Training room downstairs, an empty room. Perhaps with all desktops opened on the Open Targets Platform page (or would that be OTT?).

2) I’d list the upcoming events first as this is the most important message in that page, followed by requesting their own workshop, then the "Getting started with the Platform".

3) I have mixed feelings about the form to request a training session. Will have a think about this.

4) I’d include some feedback (anonymised) from previous workshops as it can show the advantages of attending/hosting a session.

5) I’d include links to the YouTube page and other social media channels. Similar to what you have done for the About page.

6) I’d not have my picture/biography in there. I’d rather have a link to the Launching of OTO (Open Targets Outreach) blog post.

7) I’d like to have the past events listed in there as well.

Thanks once again.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #27](https://github.com/opentargets/platform/issues/27) via [**ZenHub**](https://www.zenhub.com/)
