### ISSUE TITLE
fetching recent blog posts is broken

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#139]
In the netlify deployment preview the recent blog posts don't show up. 
I am not sure why this is because @mkarmona nginx settings seem to work in production.

Regardless, I have enabled the ghost API on the blog as an alternative to RSS. @LucaFumis had explored this before, but i couldn't get the settings turned on. 

I followed the instructions here https://api.ghost.org/docs/ajax-calls-from-an-external-website#1-granting-access-to-your-domain so that one should be able to use the Ghost API [docs here](http://themes.ghost.org/docs/ghost-url-api) from www.targetvalidation.org and proxy.targetvalidation.org

It should be as easy as copy/pasting this:
```html
 <script type="text/javascript" src="/shared/ghost-url.min.js?v=0a3b27d889"></script>
<script type="text/javascript">
ghost.init({
	clientId: "ghost-frontend",
	clientSecret: "a9fe83f50655"
});
</script>
```

This is low priority considering that somehow this works in production.

**Comment by LucaFumis** [comment]
Thanks Eliseo - I'll have a look: it would be good to get the webapp working with the API rather then the RSS.

**Comment by emepyc** [comment]
@eliseo, do you have any update on this? I suppose this is higher priority now that we plan to deploy production in netlify

**Comment by elipapa** [comment]
no update from me. i enabled the ghost API and the snippet above should work... i don't think @LucaFumis had the time/chance of testing it yet. 
i can try making a PR on the webapp if it would help?

**Comment by emepyc** [comment]
Thanks @elipapa, don't worry I'll try that snippet

**Comment by LucaFumis** [comment]
Hi, back today - I'll look into this as a priority

**Comment by elipapa** [comment]
`/shared/ghost-url.min.js return a 404 and Public API is not working` is an error, probably due to my nginx proxy settings in front of the blog. Some other people encountered it here: https://github.com/TryGhost/Ghost/issues/6676

I will try to fix the proxy settings (which live here https://github.com/opentargets/infrastructure/blob/master/blog.opentargets/docker-compose.yml)

**Comment by elipapa** [comment]
http://blog.opentargets.org/shared/ghost-url.min.js works and returns:

```sh
!function(){"use strict";function a(a){var b,c=[];if(!a)return"";for(b in a)a.hasOwnProperty(b)&&(a[b]||a[b]===!1)&&c.push(b+"="+encodeURIComponent(a[b]));return c.length?"?"+c.join("&"):""}var b,c,d,e,f="https://blog.opentargets.org/ghost/api/v0.1/";d={api:function(){var d,e=Array.prototype.slice.call(arguments),g=f;return d=e.pop(),d&&"object"!=typeof d&&(e.push(d),d={}),d=d||{},d.client_id=b,d.client_secret=c,e.length&&e.forEach(function(a){g+=a.replace(/^\/|\/$/g,"")+"/"}),g+a(d)}},e=function(a){b=a.clientId?a.clientId:"",c=a.clientSecret?a.clientSecret:"",f=a.url?a.url:f.match(/{\{api-url}}/)?"":f},"undefined"!=typeof window&&(window.ghost=window.ghost||{},window.ghost.url=d,window.ghost.init=e),"undefined"!=typeof module&&(module.exports={url:d,init:e})}();
```

**Comment by elipapa** [comment]
@LucaFumis i have not [added](https://api.ghost.org/docs/ajax-calls-from-an-external-website#1-granting-access-to-your-domain) netlify.com to the allowed domains.. that might be the issue

**Comment by LucaFumis** [comment]
Blog feed working with Ghost API in Netlify:
https://blog-api--paratrooper-antelope-70721.netlify.com/

loading 5 posts only - can set the limit in the html if we want more or less (with 3 posts we almost wouldn't need the scrollbars)

**Comment by LucaFumis** [comment]
If we're happy with it, we can merge I guess?

**Comment by emepyc** [comment]
I think it is working fine, do you mind merging and closing this issue?

**Comment by LucaFumis** [comment]
Merged into master branch.
