### ISSUE TITLE
Our links to Expression Atlas are obsolete

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#140]
![image](https://user-images.githubusercontent.com/1447134/27071532-48ef3710-5015-11e7-84de-f348645c5f24.png)

e.g. http://www.ebi.ac.uk/gxa/experiments/E-MEXP-1878/Results?geneQuery=ENSG00000129824

The general URL is http://www.ebi.ac.uk/gxa/experiments/E-MEXP-1878/Results

After entering the gene of interest on the search box the resulting URL is:
http://www.ebi.ac.uk/gxa/experiments/E-MEXP-1878/Results?specific=true&geneQuery=%255B%257B%2522value%2522%253A%2522ENSG00000129824%2522%257D%255D&filterFactors=%257B%257D&cutoff=%257B%2522foldChange%2522%253A1%252C%2522pValue%2522%253A0.05%257D&regulation=%2522UP_DOWN%2522

**Comment by emepyc** [comment]
Issue moved to [opentargets/data_pipeline #150](https://github.com/opentargets/data_pipeline/issues/150) via [**ZenHub**](https://www.zenhub.com/)
