### ISSUE TITLE
Show homology scores as Table in target profile page

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#143]
This was recommended by GSK Safety experts during the targethon in Ware as an alternative view to the gene tree. 

Example from Homologene:
https://www.ncbi.nlm.nih.gov/homologene?cmd=Retrieve&dopt=AlignmentScores&list_uids=101663 

<img width="1280" alt="homologene-screen shot 2017-05-10 at 08 48 41" src="https://user-images.githubusercontent.com/20280139/27435526-58f7ea9e-5754-11e7-8a10-d04375cf109e.png">

Species of interest for Safety:
- minipig (main species) 
- zebrafish 
- rodent 
- dog
- monkey

**Comment by emepyc** [comment]
This is now included in this deploy preview.
https://homologues--paratrooper-antelope-70721.netlify.com/target/ENSG00000157764

If we don't have any issue with this, I'll merge in the next release

**Comment by emepyc** [comment]
Done and released
