### ISSUE TITLE
In the literature evidence table the link in the title points to the homepage

### ISSUE THREAD

**Issue by emepyc** [opentargets/webapp#144]
Clicking on the title opens a new tab loading the paper in europepmc, but right-clicking on the title and clicking on "Open Link in New Tab" points to the home page of OT.

This is probably happening because we respond to 'click' events in the title creating the link and calling it.
It would be better to have the links as real links in the DOM

**Comment by LucaFumis** [comment]
Fixed this in commit 274ba33
