### ISSUE TITLE
move tracker code to separate file to allow deploy specific tracker code

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#145]
move the tracker code to its own js file would make it easier to mount it as a separate file when deploying. eg. `docker run -v /path/to/local/piwik/token:/app/external/piwik/js webapp`

kind of the same way we do for certificates, but probably better in a separate stand-alone directory

**Comment by andrewhercules** [comment]
Triage notes:

- Piwik code moved to its own file in [app/piwik.js](https://github.com/opentargets/webapp/tree/master/app)
- Can do the same with the Google Analytics code currently found on [lines 337 to 354 of app/index-tmpl.html](https://github.com/opentargets/webapp/blob/master/app/index-tmpl.html#L337)

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #29](https://github.com/opentargets/platform/issues/29) via [**ZenHub**](https://www.zenhub.com/)
