### ISSUE TITLE
Download button at the bottom of page in large browser window

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#146]
The download icon button on the bubbles view appears at the bottom of the page opposite the legend when the browser window becomes wider that ~1450px on my home monitor.

![screen shot 2017-06-26 at 10 15 29](https://user-images.githubusercontent.com/20280139/27554329-025ca620-5aa6-11e7-9b13-fa7e51f8c952.png)
It's at the right place when the browser window is the following size:
Browser window width:	1422
Browser window height: 1017

![screen shot 2017-06-26 at 10 15 40](https://user-images.githubusercontent.com/20280139/27554339-06c76628-5aa6-11e7-9e48-b7eca6a6f0f5.png)
But it moves below the bubbles view when the browser window becomes larger:
Browser window width:	1504
Browser window height: 1078

![screencapture-targetvalidation-org-target-ensg00000142192-associations-1498466898451](https://user-images.githubusercontent.com/20280139/27554398-34247890-5aa6-11e7-9164-a6112b17a0e2.png)
It also appears at the bottom when I use the full page screen capture extension.

But it stays at the right place in the other two views (Table and Tree) in a larger window and when the bubbles view is viewed on my laptop screen.

Chrome Version 58.0.3029.110 (64-bit)

Monitor: NEC multisync lcd2190uxp (resolution 1600 x 1200) 
http://www.nec-display.com/ap/en_display/lcd2190uxp/

**Comment by peatroot** [comment]
I've only observed this on small window widths, which is unlikely to affect many users. Closing.
