### ISSUE TITLE
Missense variants not visible in genome browser

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#148]
3 mutations with rsId are presented on this page, however, they are not visible on the genome browser view

http://www.targetvalidation.org/evidence/ENSG00000133703/EFO_0000178

**Comment by emepyc** [comment]
The mutations are there, but just below other mutations. You just need to zoom in to reveal the red lollipops.
To make this more clear, if a group of snps contain a red one I'm now colouring the label red (in beta).
Let me know if this solves the issue for now. If not, please re-open.
