### ISSUE TITLE
Uniprot protein widget links out to diseases in Uniprot

### ISSUE THREAD

**Issue by iandunham** [opentargets/webapp#152]
Using the protein browser widget, we can see variants in disease. The popup lists details of the variant and disease, but clicking on the disease takes us to Uniprot rather than our disease page. Can we change these to link back to our evidence page corresponding to this target and disease? Or the disease page? We may need some mapping of the term they have in the widget (but we should have this already).

**Comment by emepyc** [comment]
I've been talking with Xav about this. They will try to include an option in the next version of the widget. I'll follow up with them

**Comment by ElaineMcA** [comment]
Widget being updated by Uniprot.  Closing until scope clarified.

**Comment by iandunham** [comment]
Hav we checked the status with Xav? I know the new version supports a variety of different features including controlling the tracks that you can display - we might want to make use of that
