### ISSUE TITLE
'Try search' in "Free data access" section of homepage 

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#153]
When clicking on 'try search' it takes one back to the top of the homepage.

Is that useful at all? 
I'd recommend pointing to our GIF animation (http://imgur.com/a/LKDhp).

Or http://targetvalidation.org/about#getting_started?   

![screen shot 2017-07-10 at 10 36 45](https://user-images.githubusercontent.com/6472381/28011847-aade9bc2-655b-11e7-91df-09bbaf7949e5.png)

p.s. we will have a nicer video recorded soon-ish as a better alternative for the GIF.

**Comment by deniseOme** [comment]
On the same section of the HP I'd suggest having:

Explore our API (instead of Explore the API).
Go to our downloads (instead of Go to downloads).

Down on that page we do say 'Our story' so it'd be good for consistency to use 'our' whenever we can, I believe.

**Comment by emepyc** [comment]
I agree the `Try search` link is a bit odd. Between the proposed alternatives I would prefer the GIF animation over the dry text of the `getting_started`. Please update this issue when the new video is available.

**Comment by deniseOme** [comment]
Cool.
Will we go with the GIF for the time being?

Or change this only when the video is ready?

**Comment by LucaFumis** [comment]
Well the idea was that it takes you to the top where the search box is, so that one can try and search... (ideally there would be some highlight and small popup next to it... but we don't have anything avail at the moment)
So happy to change to any of the other two options (no strong preference)

**Comment by peatroot** [comment]
@deniseOme, is the video ready? If not, suggest we close this owing to justification by @LucaFumis.

**Comment by deniseOme** [comment]
Yes, it is ready:
https://www.youtube.com/watch?v=TdTI_biupFA

**Comment by peatroot** [comment]
Great, thanks @deniseOme!

**Comment by peatroot** [comment]
I've just added the video tutorial to the outreach page (see https://github.com/opentargets/webapp/issues/138), so rather than duplicate the video, I'm going to close this following @LucaFumis's justification above.
