### ISSUE TITLE
footer on the HP

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#155]
Can we update the current:

'Terms of use & privacy'

to either

'Terms of use and privacy'

or the preferred 'Terms of use' only?

Although the privacy theme is dealt on the page /terms_of_use, the page itself is not entitled "Terms of use and privacy".

Besides, there is already a section in the HP just above the footer that says 'Concerned about privacy?'

**Comment by emepyc** [comment]
Fixed in beta now
