### ISSUE TITLE
linkouts to Ensembl landing on a weird page 

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#156]
From this:

http://beta.opentargets.io/evidence/ENSG00000206172/Orphanet_93616?view=sec:genetic_associations

when I click on the Ensembl link I land on a weird page (both production and beta) in google and firefox.

The URL seems to be the correct one i.e.g 

http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000206172;r=16:176680-177522

![screen shot 2017-07-10 at 14 27 23](https://user-images.githubusercontent.com/6472381/28020410-310d01be-657c-11e7-87ca-dd7848fabb07.png)

**Comment by emepyc** [comment]
It seems Ensembl has stopped working properly with https (try [https://www.ensembl.org/index.html](https://www.ensembl.org)).
I have changed the links to point to http. Should work in beta now.
