### ISSUE TITLE
size of the genomic interval shown in evidence page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#157]
The browser view for HBA shows a region of ~ 2,2 kb with plenty of empty space upstream HBA.

Why is that?

The region is not fixed (i.e. always 2.2 kb regardless the gene.

Due to the overlapping red lollipops, would it be better to have a more zoomed in version of the HBA region e.g.:

![screen shot 2017-07-10 at 14 36 29](https://user-images.githubusercontent.com/6472381/28020678-27fe5810-657d-11e7-942e-f02645f0dfe7.png)

rather than:

![screen shot 2017-07-10 at 14 31 34](https://user-images.githubusercontent.com/6472381/28020704-3802e302-657d-11e7-9d59-08d44ff0a9d1.png)

?

**Comment by emepyc** [comment]
The genome browser sets automatically the zoom to show all the mutations. Note the one on the left side of the upper track.
Maybe the solution is to give a bit more (rather than less!), to make the mutation on the left more evident
