### ISSUE TITLE
write information for the new `details` column in the genetic evidence panel

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#162]
It would be nice to have a column info box, similar to:

![image](https://user-images.githubusercontent.com/112610/28516840-79674a6c-705a-11e7-90e6-013b2f80fa52.png)

that reads something similar to:

> Additional details about each evidence. Specific data depends on the data source included. 
PheWAS catalog data will have *odds ratio* - the relative ratio of ... and *cases* - the number of cases that ... _

**Comment by andrewhercules** [comment]
@deniseOme, is this something you'd like us to prioritise for the upcoming release? If so, could you please provide @LucaFumis and I with the text you'd like us to use?

**Comment by deniseOme** [comment]
I'm a bit confused. Not sure where @elipapa's suggested text would go.

Could you please point me to the page please?

**Comment by andrewhercules** [comment]
I think it comes from the Diseases Associated table on the batch search page

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #30](https://github.com/opentargets/platform/issues/30) via [**ZenHub**](https://www.zenhub.com/)
