### ISSUE TITLE
one way to write p value

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#163]
From wikipedia:

"Depending on which style guide is applied, the "p" is styled either italic or not, either capitalized or not, and either hyphenated or not. For example, AMA style uses "P value," APA style uses "p value," and the American Statistical Association uses "_p_-value.""

I've seen _P_-value too in papers e.g. https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwiAxaGu0aHVAhWcOsAKHUjtD8wQFggvMAE&url=http%3A%2F%2Fwww.nature.com%2Farticles%2Fnature05911&usg=AFQjCNEX0YH68lJHGwD7j7sIxJfjD9BDTw

I have no preference but consistency would be good throughout the website.

**Comment by emepyc** [comment]
We can include this in the consts service and refer to that throughout. I suggest p-value.

**Comment by LucaFumis** [comment]
I've added this to the dictionary (json) and updated the _table headings_ on the evidence page.
I'll go thorough tables content and other pages.
