### ISSUE TITLE
extra column in evidence page: PheWAS and GWAS

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#164]
@elipapa has proposed a couple of changes to the genetic evidence table based on the new PheWAS data e.g.

https://phewas-catalog-test--paratrooper-antelope-70721.netlify.com/evidence/ENSG00000146648/EFO_0003952

We need to provide the summary statistics (e.g. cases, odds ratio). This info is not available through the PheWAS website. So linking the evidence page to the original source is not an option, @nikiforosk @iandunham @jcbarret.

A new column has been proposed by @elipapa @emepyc that would contain the addition info, which is evidence-specific. A screenshot of this will be available soon.

The questions are:

How will we populate the same column for GWAS? 
Will we leave the column empty? 
Yes, we could and explain the reason if/when users complain.

Or will we provide these stats as well for GWAS?
Yes, we could. Users have already asked us in the past to provide odds ratio and confidence intervals for GWAS. At the time we pointed them to Ensembl where they have the details. 

If we decide to provide OR, CI or/and beta-coefficient for GWAS to be consistent with what is provided for PheWAS, @ckongEbi would have to liaise with Olga et al, as this info is not given to us yet.

**Comment by iandunham** [comment]
I think it may be best to have a separate table for the Phewas if
      we really want the cases. The odds ratio we can get for GWAS
      traits but the cases for the Phewas data has a specific meaning
      e.g. 25 means that 25 of the 13,835 patients in the Phewas study
        had the phenotype. In the GWAS studies we would generally have a
        specific number of patients and matched controls. So putting the
        two together will be misleading.
    In both cases
        the sample size (cases) is reflected in the potential values
        that the OR and p value can take, so it might be better to have
        the OR and 95% CI as this avoids the user having to work out
        what effect the case number would have other than hand waving
        saying it's a small number of cases. These are available in
        Supplementary Table 8 of the paper. Having these and not the
        cases would enable both data to readily fit in the same table.
      
    For GWAS we do
        use the population size to assess whether the study is reliable,
        but this is encapsulated in the score in a relatively low
        resolution way. Ask Olga for the OR and CIs, but we will also
        need to make sure we get these for the other GWAS sources via
        postgap.
      
    
    On 24/07/2017 11:10, deniseOme wrote:
    
    
      @elipapa has proposed a couple of
        changes to the genetic evidence table based on the new PheWAS
        data e.g.
      https://phewas-catalog-test--paratrooper-antelope-70721.netlify.com/evidence/ENSG00000146648/EFO_0003952
      We need to provide the summary statistics (e.g. cases, odds
        ratio). This info is not available through the PheWAS website.
        So linking the evidence page to the original source is not an
        option, @nikiforosk @iandunham @jcbarret.
      A new column has been proposed by @elipapa @emepyc that would contain the
        addition info, which is evidence-specific. A screenshot of this
        will be available soon.
      The questions are:
      How will we populate the same column for GWAS?
        Will we leave the column empty?
        Yes, we could and explain the reason if/when users complain.
      Or will we provide these stats as well for GWAS?
        Yes, we could. Users have already asked us in the past to
        provide odds ratio and confidence intervals for GWAS. At the
        time we pointed them to Ensembl where they have the details.
      If we decide to provide OR, CI or/and beta-coefficient for GWAS
        to be consistent with what is provided for PheWAS, @ckongEbi would have to liaise with
        Olga et al, as this info is not given to us yet.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opentargets/webapp","title":"opentargets/webapp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opentargets/webapp"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"extra column in evidence page: PheWAS and GWAS (#164)"}],"action":{"name":"View Issue","url":"https://github.com/opentargets/webapp/issues/164"}}}

**Comment by andrewhercules** [comment]
Triage notes:

- Related to [issue #141 in opentargets/roadmap repo](https://github.com/opentargets/roadmap/issues/141)
- Have identified this as a suitable feature for a mini-release
- Will require creating a new column in the Common Diseases table and exposing data.unique_association_fields.odd_ratio and data.unique_association_fields.confidence_interval if available
- Data already available from OT API - see sample API response for NOD2 and Crohn's disease

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #28](https://github.com/opentargets/platform/issues/28) via [**ZenHub**](https://www.zenhub.com/)
