### ISSUE TITLE
typographic changes

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#166]
Genomics england ==> Genomics England
PHEWAS ==> PheWAS

**Comment by elipapa** [comment]
@deniseOme may have more suggestions

**Comment by deniseOme** [comment]
see #163

**Comment by deniseOme** [comment]
Top right menu has PanelAPP. It should be PanelApp.

**Comment by deniseOme** [comment]
on staging.

**Comment by deniseOme** [comment]
http://staging.targetvalidation.org/evidence/ENSG00000167207/EFO_0003767 still has PHEWAS rather than PheWAS (in the browser tab)

**Comment by deniseOme** [comment]
Hi @LucaFumis, not sure if we expected to see PheWAS already? !?!?!?

**Comment by deniseOme** [comment]
Under Clinical significance, can we have consistency: first letter lower case always (or upper case) please? e.g. pathogenic/protective or Pathogenic/Protective

<img width="1178" alt="screen shot 2017-07-25 at 16 47 45" src="https://user-images.githubusercontent.com/6472381/28581060-2ca28a16-7159-11e7-9270-aad9f61e50ca.png">

**Comment by LucaFumis** [comment]
The first two issues (GE, phewas) were actually fixed and pushed to production a couple of weeks ago.

About the Pathogenic vs protective: we don't modify the case of content coming from the API, so I'd imagine this kind of issue could also happen in other tables / cols.
I'll change it to lower case, but perhaps we can review quickly all the tables after the holidays.

**Comment by emepyc** [comment]
All the frontend changes made, if there is any change in the data we should open an issue there
