### ISSUE TITLE
searching for 'm', table, BRAF associations...

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#168]
...does not give melanoma as the QC spreadsheet implies:

https://docs.google.com/spreadsheets/d/1x0fNHWihX_OHdFu7QpFOGQHqpDhFG__nQxn5LgUXE0A/edit#gid=1921435587
<img width="1042" alt="screen shot 2017-07-25 at 21 19 41" src="https://user-images.githubusercontent.com/6472381/28591847-ff5e2a08-717e-11e7-940f-a6bfecf5fb23.png">

Searching for 'mel' works beautifully. Searching for 'me' works ok.
<img width="1040" alt="screen shot 2017-07-25 at 21 20 48" src="https://user-images.githubusercontent.com/6472381/28591888-2664e100-717f-11e7-9a25-717259f1bd72.png">

Same applies for searching for "h" or "htt" hopping to get "htt" gene only here:

http://beta.opentargets.io/disease/Orphanet_399/associations

Btw, this does not work on production either. So perhaps something we can't do anything about it right now??!?!?

**Comment by apierleoni** [comment]
this is for the api
yes we can disable the ability to search fo a single char, because elasticsearch will not give the expected results for a query this generic

**Comment by deniseOme** [comment]
Ok. Thanks. I will remove the actions for searching for one or two letters from the QC document:

https://docs.google.com/spreadsheets/d/1x0fNHWihX_OHdFu7QpFOGQHqpDhFG__nQxn5LgUXE0A/edit#gid=1921435587

Should we still expect to work for "mel" and get melanoma, then "htt" and get htt only?

**Comment by apierleoni** [comment]
Yes they should work

Il 26 lug 2017, 10:45 +0100, deniseOme <notifications@github.com>, ha scritto:

**Comment by emepyc** [comment]
Issue moved to [opentargets/rest_api #92](https://github.com/opentargets/rest_api/issues/92) via [**ZenHub**](https://www.zenhub.com/)
