### ISSUE TITLE
include version numbers on release notes for 17.06/3.2

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#169]
Things such as EFO version 2.84, COSMIC version 81, EVA, ClinVar April release number collected from here:

https://github.com/opentargets/data-providers-docs/wiki/Data-(Evidence-Strings)-Submission-Process

Should go in the release notes, not blog as it's too much of dry piece of info.
Note we have not included those in the past, AFIK.

So if we decide to include them now, we should do it onwards too for consistency.

As per the first release in netlify, I suggest it on the release notes rather than blog.
The same for orthologues table, web bug fixes and protein/RNA expression data.

What do you think @emepyc @elipapa?

**Comment by deniseOme** [comment]
Also I will point the release blog post to the release notes for more details.

**Comment by emepyc** [comment]
We can include versions for the data sources in the release notes. Another place is the data sources doc.
As for the netlify, it is transparent to the user and I don't see it very useful from a user point of view.
The current release notes for 3.2 already includes the orthologues table, bug fixes, etc

**Comment by peatroot** [comment]
@deniseOme, the URL above does not work anymore. Do you know where this information has moved to? The provider versioning does not appear to be in the release notes, but I agree it'd be useful for future versions.

**Comment by andrewhercules** [comment]
Moving issue to the [data_release repository](https://github.com/opentargets/data_release) as data provider version numbers could be integrated into the [Data Metrics & Plots wiki page](https://github.com/opentargets/data_release/wiki/Data-Metrics-&-Plots) and the webapp could link directly to that wiki once the version numbers are available.

**Comment by andrewhercules** [comment]
Issue moved to [opentargets/data_release #89](https://github.com/opentargets/data_release/issues/89) via [**ZenHub**](https://www.zenhub.com/)
