### ISSUE TITLE
linking out to OMIM and HGNC pages

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#171]
I've started a page with possible DBs to link out to us:

https://docs.google.com/spreadsheets/d/10COpZhOqvgFHxGNxrnZ_4j9XmUshLH7rcsOUhbwDXDQ/edit?usp=sharing

The DBs belong to four categories:

(A) those that we have widgets/or data for in our pipeline
e.g. **GTEx** and **Genomics England PanelApp**, respectively

(B) those  that we don't have their data (per se) but it's worth linking to them regardless
e.g. **OMIM** and **HGNC**

(C) those that we'd like to get data from in the future
e.g. **ExAC** (watch this space @ckongEbi)

(D) other
e.g. **RNA Central** (wait till we get better coverage of non-coding targets associated with diseases or if they move towards a disease/phenotype focus); **Wikipedia**

@iandunham and I have gone through most of the list in the google sheet and decided on the actions.

For category B), we need to link out to them first for them to do the reverse i.e. link out to us.

**HGNC**: @iandunham's suggested we add 'see BRCA2 in HGNC' or something along these lines whatever fits best from the UX and UI points of view, @nikiforosk @LucaFumis @emepyc @peatroot (from the target profile page).

For OMIM, we need their ID displayed (from target and/or disease profile pages).

Once we have OMIM and HGNC we are in a stronger position to go and ask them to link to the Open Targets Platform to get traffic from their websites to ours.

In the meantime I will contact dbs from category (A) and investigate the Wikipedia option.

**Comment by peatroot** [comment]
Closing and moving to `data_pipeline`: https://github.com/opentargets/data_pipeline/issues/249.
