### ISSUE TITLE
Literature/bibliography treemap visualizations

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/webapp#176]
We've been working on some treemap visualisations to explore bibliography data.
There are 3 versions available on the target profile page:
- Bibliography Treemap - the first version which we've reviewed with users in a UX session
- Bibliography chips - based on Google image search "chips"
- Bibliography Treechip - a treemap with "chips" instead of breadcrumb

These can be viewed here: https://treemap-new--paratrooper-antelope-70721.netlify.com/target/ENSG00000157764

At the moment the mix treemap+chips seems to be the favourite

**Comment by elipapa** [comment]
@deniseOme we should announce this is now available.

**Comment by deniseOme** [comment]
I can highlight this on social media when it's pushed live.
Just talked to @LucaFumis about it. Feature yet to be included in the disease and drug summary pages.

However don't we want to save this for the release blog post?

**Comment by elipapa** [comment]
completely up to you where and when to do it. i was only trying to flag it

________________________________
