### ISSUE TITLE
point to the original sources of data in profile pages

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#177]
As discussed on slack (random channel), we have to add one a link to Ensembl and hyperlink Protein trees and ortologues under Gene trees.

We should be consistent across all those tabs saying where the data comes from. Sub tabs within a tab needs to be populated as well.

**Comment by andrewhercules** [comment]
Flagging this for inclusion in our next mini-release. @LucaFumis, I'll create a document with the description and source link and get the team to review before we implement.

**Comment by LucaFumis** [comment]
I've added the link for protein trees and ortologues under Gene trees. Will wait for the list of description + source links for the other part. Marking as "needs info".

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #25](https://github.com/opentargets/platform/issues/25) via [**ZenHub**](https://www.zenhub.com/)
