### ISSUE TITLE
Point to our own drug page from drug evidence?

### ISSUE THREAD

**Issue by iandunham** [opentargets/webapp#178]
Should we point the link to a drug on the evidence page to our own internal drug page rather than direct to ChEMBL?  Our drug page has a linkout to ChEMBL, but we are only using this for batch search at the moment

![untitled](https://user-images.githubusercontent.com/1729980/29276498-b6912a22-8106-11e7-841e-668b7671be02.png)

**Comment by emepyc** [comment]
We now link to that page from the evidence drug table (in the evidence page and profile pages)
