### ISSUE TITLE
GTEx not loading from target profile page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#179]
@elipapa  and I have noticed GTEx widget does not load. @emepyc @peatroot @iandunham unable to replicate the issue. 

I've tried it with google chrome (Version 59.0.3071.115 ) and safari (Version 10.1.2 (11603.3.8)) and neither works:

<img width="962" alt="screen shot 2017-08-15 at 09 51 51" src="https://user-images.githubusercontent.com/6472381/29310943-aa7b6b3e-81a7-11e7-9ac2-25e2f3424e40.png">

<img width="1052" alt="screen shot 2017-08-15 at 10 52 59" src="https://user-images.githubusercontent.com/6472381/29310967-c9d26de8-81a7-11e7-9be9-d7defab5f795.png">

It works for me in firefox:
<img width="775" alt="screen shot 2017-08-15 at 10 55 35" src="https://user-images.githubusercontent.com/6472381/29311050-239e13f4-81a8-11e7-9f46-92909cd8dfac.png">

When I click on the GTEx link in our profile page, it takes me to the GTEx homepage with a warning:

<img width="772" alt="screen shot 2017-08-15 at 10 54 34" src="https://user-images.githubusercontent.com/6472381/29311028-1199d148-81a8-11e7-815a-4998133f1e8d.png">

**Comment by deniseOme** [comment]
Note from @apierleoni: "to put a monitor for the gtex api in runscope, so we know when and what is failing. If it fails too often we can serve the data ourselves".

**Comment by emepyc** [comment]
Should be fixed now for some time. Feel free to reopen if there is any other problem
