### ISSUE TITLE
include the title of batch search in the landing page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#181]
Batch Search landing (https://www.targetvalidation.org/batch-search) and results (https://www.targetvalidation.org/summary?targets=73756,95303,108219,198369,105401,134882,104998,181915,105397,178623,107968,133195,171522,116288,169508,143365,95110,109787,179344,153064,108094,116833,151151,111537,114859,12779,169220,103375,189067,108423,133703,138031,178828,197114,130592,100368,164308,111424,108688,181634,164512,182256,113327,163285,79263,115232,100311,143622,167207,187796,85978,162594,90339,5844) page have no title.

We should include a title and an explanation e.g.

http://www.uniprot.org/uploadlists/
http://www.uniprot.org/peptidesearch/
http://www.ensembl.org/Tools/VEP
http://www.ensembl.org/Multi/Tools/Blast?db=core
https://genome.ucsc.edu/cgi-bin/hgBlat
https://genome.ucsc.edu/cgi-bin/hgPcr?hgsid=604348409_3KkvUCISVGeWNSWjMh86LjKhVMnM

**Comment by emepyc** [comment]
The title is "Summary page for XX targets", I think that is enough since we can land to that page coming not only from uploading a list but also from other parts of the webapp that has 1+ genes
