### ISSUE TITLE
pretty 503 page

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#183]
We don't have anymore a 503.html page that could be deployed (in case the backend has some problems). 
Do we need one?

**Comment by LucaFumis** [comment]
There is `app/error503.html` - is that the one you're after?

**Comment by elipapa** [comment]
thanks, i remembered we had it. 
we also need to find a way to deploy it in netlify, if we have backend trouble.

**Comment by andrewhercules** [comment]
Triage notes:

- 503 error page already exists
- Deploying it in Netlify if we have back-end trouble is low priority

**Comment by andrewhercules** [comment]
Ticket closed as per triage notes above
