### ISSUE TITLE
allow users to subscribe to our announce list

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#185]
We have an announce list with subscribers who want to be kept in the loop for Open Targets updates.

This is maintained by Holly and available upon request

One of the ways we've been populating that list is by asking every user who contacts us on support if we can include their email addresses.

This is not ideal: A) We capture just the users contacting us on support, B) it's tedious and time consuming.

In addition to @elipapa's suggestion, mailchimp, I have this suggestion:

![screen shot 2017-08-25 at 12 08 21](https://user-images.githubusercontent.com/6472381/29715157-047dc78c-899e-11e7-9495-bc977070bc5d.png)
![screen shot 2017-08-25 at 12 09 06](https://user-images.githubusercontent.com/6472381/29715158-0480fe66-899e-11e7-9515-43805870f9c0.png)

Can we agree on one style @iandunham @emepyc @LucaFumis @elipapa ? I have no preference.

**Comment by elipapa** [comment]
one hundred times yes please!
mailchimp gives an html element that can be styled

________________________________

**Comment by deniseOme** [comment]
e.g. ![screen shot 2017-08-25 at 15 22 02](https://user-images.githubusercontent.com/6472381/29872701-9401db26-8d88-11e7-8c2a-c7411063e06f.png)

"I'd like to keep up with Open Targets updates!"

**Comment by LucaFumis** [comment]
Mailchimp that Eliseo suggested looks interesting. 
Happy to take a look at this (how to implement) and review options with Denise when she's back.

**Comment by elipapa** [comment]
we also have a hubspot integration as of yesterday and might be better to explore their form element (which will then share the user emails with mailchimp)

________________________________

**Comment by LucaFumis** [comment]
Will need to review the final option with Andrew.

**Comment by elipapa** [comment]
any reason why we haven't pushed this to production ?

**Comment by LucaFumis** [comment]
I've updated the code last week (as it was branched months ago) and are now reviewing final details with @andrewhercules so it should be ready to go soon.

**Comment by andrewhercules** [comment]
I've updated Hubspot and created a new lead generation campaign to enable the pop-up on the Platform homepage.
