### ISSUE TITLE
bubbles x tree view downloads

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#187]
When I download the bubbles view using Google chrome as png (and the 3X scale) and use that file in Twitter, the bubbles view looks great:

https://twitter.com/targetvalidate/status/894943102951096320

![screen shot 2017-08-30 at 13 49 46](https://user-images.githubusercontent.com/6472381/29873026-cd549d0e-8d89-11e7-8280-ae4e9fdc25f9.png)

The same does not apply to the tree view:
https://twitter.com/targetvalidate/status/900026535675125761

Are the thick black line around the squares/circles ok?
![screen shot 2017-08-30 at 13 48 21](https://user-images.githubusercontent.com/6472381/29872975-a838d116-8d89-11e7-9979-347bcc51ec6f.png)

**Comment by emepyc** [comment]
I have improved the export of the associations tree.
This is included now in the upcoming release
