### ISSUE TITLE
"variant" instead of "mutation" in genetics browser widget

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#188]
Yesterday I met Jeff and we were looking at the Genetic associations for SNCA - Parkinson's:
https://www.targetvalidation.org/evidence/ENSG00000145335/EFO_0002508?view=sec:genetic_associations

He mentioned that on the browser widget we should be using the term "variant(s)" instead of "mutation(s)":

![snca-pd-genetics-browser-mutations](https://user-images.githubusercontent.com/20280139/29877963-143e9062-8d99-11e7-8ca6-3c8ea4b02b85.png)

The reason for this, as far as I understood, is that mutations are variants that have not been inherited by one's parent whereas what we show in these tracks are common variants from GWAS. Although many people use both terms interchangeably, this is not correct in Jeff's view.

We also noticed that on 2nd column of the Common diseases table we use the header "Variant" while the corresponding column on the Rare diseases is called "Mutation". Jeff was OK with that (although this seems to suggest that it's OK to use "Mutations" on the 2nd track of the widget - but not on the 1st track and the legend underneath). @iandunham any thoughts?

![snca-pd-genetics](https://user-images.githubusercontent.com/20280139/29878248-dfaa2162-8d99-11e7-8b44-1e5df0bbb272.png)

**Comment by iandunham** [comment]
I think this is an oversight (we shouldn't have been using
      'mutations' in the browser for the common disease track). 
    
    The distinction we are supposed to be using is "variant" for
      common base differences that exist in a population, and "mutation"
      for changes that have been shown to associated with a significant
      phenotypic change i.e. a rare disease or a cancer for somatic
      mutations.
    There are shades of grey in this distinction though. So
      'mutation' is used in different ways across different communities
      (read the following if you want to become confused).
    For the biochemist, the act of changing the chemical nature of a
      nucleotide is a mutation. So each change is caused by a mutation
      event, although later it might be called a variation.
    For the population geneticist, the variants that are produced by
      mutation segregate in the population due to processes like
      selection and genetic drift.
    For the classical geneticist a mutation has first of all a
      recognisable phenotype that you observe in your organism of
      interest, e.g. red/white eyes in flies, a rare disease in humans,
      and you then work back to identify the base change that causes the
      phenotype, which you refer to as the causal mutation. 
    
    For the oncologist, you observe all the changes that occur in the
      somatic cells of a cancer and call them mutations even though some
      may not have phenotypes (e.g. driver and passenger mutations)
    
    For the common disease geneticists, all differences in the base
      sequence between individuals in a population are variants, until
      such time as you can show that one is causal of a phenotypic
      change, and even then you might not call it a mutation....but a
      causal variant. 
    
    So in summary the process of mutation gives rise to variants that
      might be called mutations if they have a strong phenotypic effect
      or are somatic (cancer). 
    
    
    On 30/08/2017 15:45, nikiforosk wrote:
    
    
      Yesterday I met Jeff and we were looking at the Genetic
        associations for SNCA - Parkinson's:
        https://www.targetvalidation.org/evidence/ENSG00000145335/EFO_0002508?view=sec:genetic_associations
      He mentioned that on the browser widget we should be using the
        term "variant(s)" instead of "mutation(s)":
      
      The reason for this, as far as I understood, is that mutations
        are variants that have not been inherited by one's parent
        whereas what we show in these tracks are common variants from
        GWAS. Although many people use both terms interchangeably, this
        is not correct in Jeff's view.
      We also noticed that on 2nd column of the Common diseases table
        we use the header "Variant" while the corresponding column on
        the Rare diseases is called "Mutation". Jeff was OK with that
        (although this seems to suggest that it's OK to use "Mutations"
        on the 2nd track of the widget - but not on the 1st track and
        the legend underneath). @iandunham any
        thoughts?
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/opentargets/webapp","title":"opentargets/webapp","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/opentargets/webapp"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"\"variant\" instead of \"mutation\" in genetics browser widget (#188)"}],"action":{"name":"View Issue","url":"https://github.com/opentargets/webapp/issues/188"}}}
    
    
    -- 
Cheers
Ian

Ian Dunham M.A. D.Phil
Scientific Director
Open Targets
European Bioinformatics Institute (EMBL-EBI)
European Molecular Biology Laboratory
Wellcome Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom 

Tel:  01223 492636  FAX:  01223 494468
dunham@ebi.ac.uk

http://targetvalidation.org
http://opentargets.org
http://twitter.com @DunhamReal

**Comment by deniseOme** [comment]
Jeff is not the first to be concerned with the way we interchangebly use 'variant' and 'mutation'. This was raised at the training UCL Alzheimers Res UK in July and discussed in one of our meetings where @iandunham asked me to list the places (yet to be done by me) where variants and mutations are used (the latter should be in rare disease track, and in cancer only). Ensembl calls mutations  the variants coming from COSMIC (who mantains cancer gene census) and from The Human Gene Mutation Database (http://www.hgmd.cf.ac.uk/ac/index.php). Everything else is variants.

We can choose our definition based on @iandunham's comments above and stick with it. I will draft something and circulate. Once it's agreed we can have this as a FAQ (or tool tip in the Browser view and other places).

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #31](https://github.com/opentargets/platform/issues/31) via [**ZenHub**](https://www.zenhub.com/)
