### ISSUE TITLE
Initialisation code in controllers/services should be explicit

### ISSUE THREAD

**Issue by peatroot** [opentargets/webapp#189]
## Problem
The service `otLocationState` sets up an event listener for `$locationChangeSuccess`. During refactoring, `otLocationState` was removed a dependency from `FeedbackController` and `MastheadController`, where it is not explicitly used. As a result, `otLocationState`'s initialisation code is not run, so the event handler never fired, leading to the facets not responding (on first click).

## Temporary solution
Re-add the non-obvious dependency (see https://github.com/opentargets/webapp/commit/14e71dde0477ad465b6a89c6efe8d12d6c3f577d).

## Proposed long-term solution
Services with state, like `otLocationState`, should have an explicit `init` function that is called from a central point when the app is bootstrapped.

**Comment by andrewhercules** [comment]
@peatroot and @LucaFumis, I am closing this ticket as I think this would be best resolved with a re-write and update of the webapp codebase
