### ISSUE TITLE
npm install fails with Cannot find module '/home/circleci/repo/node_modules/v8flags/cache/5.1.281.107.flags.json'

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#195]
Builds keep failing with the following error:

![image](https://user-images.githubusercontent.com/112610/30387729-63e612e0-98a5-11e7-8963-e8a02ba71100.png)

rebuilding without cache works, but it's unclear why this happens in the first place.

**Comment by emepyc** [comment]
This is a cache issue in circle ci.
I think there is a way in circle ci to clear the cache on every build. We should enable that for now
