### ISSUE TITLE
add output of relation endpoint to target profile page

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#196]

**Comment by emepyc** [comment]
Not sure if that should live in the profile page or the association page? (maybe as a new tab?)
I will explore both options.

**Comment by apierleoni** [comment]
What about the summary page?

**Comment by emepyc** [comment]
When we have one, yes it should go there. For now (we decided to expose that data asap) we need to decide if associations or profile pages. I think the associations page is a better fit (it is based on targets / diseases in common so it makes sense to display it where our specific data is shown.

**Comment by peatroot** [comment]
This is resolved by the addition of the `Similar targets (based on diseases in common)` tab of the target profile page. If it is decided to use the relation endpoint data in a different way, we should open more specific issues to reflect this.
