### ISSUE TITLE
Add expression data to batch search page

### ISSUE THREAD

**Issue by peatroot** [opentargets/webapp#198]
The RNA and protein expression data should be displayed on the target batch search page.

## Earlier design
Here's a screenshot of the first design, which I don't think was ever used in production.
![image](https://user-images.githubusercontent.com/7376272/30813448-6015cfd4-a205-11e7-805d-2ecdf126754e.png)

## Grouping of tissues
We have tissue hierarchies organised by organ and anatomical system elsewhere, which we could also use in this view.

## Ordering of genes/tissues
It may be helpful to cluster the genes and tissues. The clustering would give one scheme to order rows and columns, though other schemes such as value (row/column sums) or alphabetical might also be useful. There are some nice transitions on [this example](https://bost.ocks.org/mike/miserables/). We may want to consider displaying dendrograms/trees to the left and top (something like the final example [here](http://genomicsclass.github.io/book/pages/clustering_and_heatmaps.html)).

## Size consideration
Currently the batch search supports up to 200 targets. With the 84 tissues available, keeping the data sufficiently compressed whilst it is passed over the wire is important. The existing format for calls to the `expression` endpoint for a single target would otherwise be acceptable.

A possible way to reduce the size of the response is to use a structure roughly as follows (where the rna/protein ordering matches that within the tissues array):
```
{
  genes: {
    ENSG00000197430: {
      rna: [10, 1, 3, 1, -1, 0, 0, ...],
      protein: [2, 1, 3, 1, -1, 0, 0, ...]
    },
    ENSG00000197431: {
      rna: [10, 1, 3, 1, -1, 0, 0, ...],
      protein: [2, 1, 3, 1, -1, 0, 0, ...]
    },
    ...
  ],
  tissues: [
    {
      label: "adrenal gland",
      organs: ["endocrine gland"],
      anatomical_systems: ["endocrine system"],
    },
    {
      label: "vermiform appendix",
      organs: ["colon", "intestine"],
      anatomical_systems: ["digestive system"],
    },
    ...
  ]
}
```

The `expression` endpoint currently supports only GET requests I think, but if we could extend it to support POST requests, the above example response might be received from a POST request with the following payload:
```
{
  "genes": ["ENSG00000197430", "ENSG00000197431"],
  "flat": true
}
```

## Questions
* Should we show RNA and protein data?
* Should we show raw RNA data or bucketed strength/specificity (ideally be consistent with single target expression widget)
* What interactivity do we want?
* Any specific colouring scheme to use?
* There are 84 tissues, which will *just* fit horizontally if the labels are small, but it is not very scalable. Is this a problem?

**Comment by emepyc** [comment]
> Should we show RNA and protein data?
RNA
> Should we show raw RNA data or bucketed strength/specificity (ideally be consistent with single target expression widget)
I was thinking the same when we were discussing the single target expression widget. I agree it should be consistent, but it is a bit tricky: what would be the legend of the color scale for the cells? (some kind of normalised TPM?)
There are 84 tissues, which will just fit horizontally if the labels are small, but it is not very scalable. Is this a problem?
My understanding is that the number of tissues will not change significantly considerably, but the number of cell lines in the data can grow (considerably?) due to the blueprint data. Any idea @ckongEbi ?

**Comment by peatroot** [comment]
Targets' expression profiles should now contain `level`, `value`, `zscore` for RNA and `level` for protein. Each gene in the above suggested output should include (in some similar format):
```
ENSG00000197430: {
      rna_level: [10, 1, 3, 1, -1, 0, 0, ...],
      rna_value: [17, 0.5, 198322, ...],
      rna_zscore: [-1, 2, 5, 0, 0, ...],
      protein_level: [2, 1, 3, 1, -1, 0, 0, ...]
    },
```

**Comment by mkarmona** [comment]
here a first implementation https://github.com/opentargets/rest_api/pull/117

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #21](https://github.com/opentargets/platform/issues/21) via [**ZenHub**](https://www.zenhub.com/)
