### ISSUE TITLE
Refactor evidence page to plugins architecture

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/webapp#199]
As per title, refactor the evidence page so that each section is a webapp plugin.
Main points are:
- sections defined in config.json
- move each table to a directive
- create plugins (directives) for each section to load the relevant tables

**Comment by LucaFumis** [comment]
Preview available here for review:
https://refactor-evidence--paratrooper-antelope-70721.netlify.com/evidence/ENSG00000157764/EFO_0001642

**Comment by LucaFumis** [comment]
This changes (and update of config) have now been merged into `master`

**Comment by emepyc** [comment]
Done
