### ISSUE TITLE
Update webapp to support API url change

### ISSUE THREAD

**Issue by peatroot** [opentargets/webapp#202]
The API `master` branch will change today from using `https://<base>/api/latest/` to `https://<base>/v3/platform/`. The webapp currently splits the information across the `APIHOST` environment variable and the `cttvApi.version` parameter within the application. Proposed changes:

| State | API_HOST | cttv.version |
| -- | -- | -- |
| before | https://base/api/ | latest |
| after |  #https://base/ | v3/platform |

Related to https://github.com/opentargets/rest_api/pull/102.

**Comment by emepyc** [comment]
I don't think we should include `platform` in the version. It should be a constant when we build the urls.
I think it should go here:
https://github.com/opentargets/RestApiJs/blob/master/src/cttvApi.js

**Comment by elipapa** [comment]
Just to inform your decision, the idea is that in the future we might have `v3/literature/some/method/here` and that if either /platform methods or /literature methods change we up the major version.

cc'ing @apierleoni @mkarmona so they are aware - this change may confuse us for a long time :)

**Comment by LucaFumis** [comment]
I looked at the basic changes in the webapp code - will test against the new API when avail.

**Comment by elipapa** [comment]
i merged to master and the new URL is now reachable from master-dot-open-targets-eu-dev.appspot.com

I also made a `v2-latest` branch to preserve the status in case we need to rollback 
cc/ @apierleoni @mkarmona

**Comment by LucaFumis** [comment]
I updated webapp master branch to point to this and seems to be working:
https://master--paratrooper-antelope-70721.netlify.com
Still need to update production setting in netlify.toml

**Comment by emepyc** [comment]
Merged and working in the webapp
