### ISSUE TITLE
data sources page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#204]
We have somatic mutations coming from GenomicsEngland but under Somatic mutation on the right hand side GenomicsEngland is not a nested source.

![screen shot 2017-10-20 at 15 26 09](https://user-images.githubusercontent.com/6472381/31825664-dc9d7120-b5aa-11e7-9b89-a368f073ffc9.png)

The description under somatic is there though:
https://www.targetvalidation.org/data_sources#somatic

**Comment by iandunham** [comment]
Do we have somatic mutations from Genomics England? I thought this was all Mendelian diseases?

**Comment by deniseOme** [comment]
Yes, we do.
I checked it before.

RET is a good example.

https://www.targetvalidation.org/evidence/ENSG00000165731/Orphanet_29072?view=sec:genetic_associations

The 100K project will have rare disease patients (their families) and cancer patients:
https://www.genomicsengland.co.uk/the-100000-genomes-project/

**Comment by deniseOme** [comment]
What I'm trying to find out is if PheWAS has cancer phenotypes too, and whether or not those are in the Platform.

And yes it does, and we have examples in the Platform:
https://www.targetvalidation.org/evidence/ENSG00000146648/EFO_0000311?view=sec:genetic_associations

**Comment by deniseOme** [comment]
Ok, the ones coming from GE and PheWAS are predisposition (not somatic).
Will keep an eye on more examples and expert input on cancer (whether medulloblastoma is hereditary or not, for instance).

https://www.targetvalidation.org/evidence/ENSG00000165731/Orphanet_276161?view=sec:genetic_associations
https://www.targetvalidation.org/evidence/ENSG00000139618/EFO_0000326?view=sec:genetic_associations
