### ISSUE TITLE
type of IDs accepted on batch search

### ISSUE THREAD

**Issue by emepyc** [opentargets/webapp#206]
@deniseOme commented on [Mon Oct 23 2017](https://github.com/opentargets/platform_issues/issues/37)

Can we state which IDs are accepted by the tool (e.g. HGNC, UniProt, ENSG IDs, synonyms) somewhere next to "List format is one target per line. A maximum of 200 targets is currently allowed."

<img width="534" alt="screen shot 2017-10-23 at 17 35 26" src="https://user-images.githubusercontent.com/6472381/31901129-79f1ee50-b818-11e7-8113-5ddbcb745b30.png">

**Comment by LucaFumis** [comment]
So this is just some text (list) to be added to the batch search page, right?

**Comment by emepyc** [comment]
Yes, I think so
