### ISSUE TITLE
When invoking Expression Atlas widget and passing a gene for gene query, say you want "symbol"

### ISSUE THREAD

**Issue by wbazant** [opentargets/webapp#211]
Consider the page for TNNI3: https://www.targetvalidation.org/target/ENSG00000129991 -> click on RNA baseline expression -> Uhlen’s lab to go to this experiment page. In that page Expression Atlas displays three genes (TNNI3K, TNNI3, FPGT-TNNI3K) instead of the only one that we have searched for TNNI3.  

I think this is because you invoke the widget with geneQuery=TNNI3.
We'd hope you instead do one of:
```
geneQuery=[{"value":TNNI3,
 "category":"symbol"}]
geneQuery=ENSG00000129991
```

This will improve the accuracy of the results (you are also showing the data for the other two genes).

**Comment by emepyc** [comment]
Thanks @wbazant 
I have now changed the way we call the widget. Will be deployed next week
