### ISSUE TITLE
consistency target profile page: Protein information

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#215]

**Comment by LucaFumis** [comment]
There's a bunch of these tickets #215 through to #225 addressing the same issue for the target profile page: could you please add some more info? just add it to one of the tickets. Or maybe have a quick chat

**Comment by deniseOme** [comment]
Thanks for looking at these.
These were created upon Miguel's request following this conversation in Nov 2017:

Some have been addressed by @emepyc already (e.g. removed the UniProt name from the title).

A) Shall we include the a link to external data throughout the description of these tabs?
It's for some (e.g. UniProt, but no for others e.g Variant, isoforms and genomic context)

B) Could all widgets be downloaded?
As it stands: gene tree can be downloaded but not protein interactions. Is there a technical issue for this? All third party widgets are downloadable but not ours…

**Comment by emepyc** [comment]
All our widgets are downloadable (bubbles view, associations tree, gene
tree, genome browser, etc...)
There are exceptions. For example, the new "related targets" or "related
diseases" because it is a multi-step widget (What do you want to download?
One option is to download "what you are seeing", adding that functionality
is trivial following the rest of the examples).
I don't remember if there is a problem exporting the protein interactions
widget. We have recently changed that widget to be plot on a mix of
canvas + svg. I'm not sure we made the download working though. @peatroot
do you remember?

**Comment by deniseOme** [comment]
Good point about the dynamic nature of the relations widget.
The GTEx plot can not be downloaded at the moment.

The protein interactions can be downloaded now in both profile page and batch search results, which it was not the case in the past as far as I can remember.

![screen shot 2018-01-17 at 09 37 44](https://user-images.githubusercontent.com/6472381/35052227-01b8a378-fb9f-11e7-8cc3-9b1ff4fcd96f.png)

**Comment by emepyc** [comment]
The GTEX plot can be exported:
https://github.com/opentargets/webapp/blob/master/app/plugins/baseline-expression/baseline-expression.html#L21

But for some reason the "export button" is not showing up in the page

<img width="961" alt="screen shot 2018-01-17 at 17 13 40" src="https://user-images.githubusercontent.com/473962/35056573-220d0d16-fbaa-11e7-918d-eb8629d6a358.png">

**Comment by peatroot** [comment]
Closing all others (with reference to this issue) for conciseness.

**Comment by andrewhercules** [comment]
Flagging this one for inclusion in our next mini-release. 

I also noticed that the GTEx export button is not visible. Based on reviewing the [code referenced by Miguel](https://github.com/opentargets/webapp/blob/master/app/plugins/baseline-expression/baseline-expression.html#L21), it looks like the <png> tag should be <ot-png> as that is how [the other downloadable widgets are tagged](https://github.com/opentargets/webapp/search?q=ot-png&unscoped_q=ot-png).

The consistency issue - naming, source referencing, etc. - has also been raised in issue #177.

**Comment by LucaFumis** [comment]
Download button is now working for the GTEx widget, so marking as fixed.
