### ISSUE TITLE
Genomics England evidence data has an invalid publication field

### ISSUE THREAD

**Issue by emepyc** [opentargets/webapp#226]
This required a hack in the webapp to look for the incorrect value ('NA')

https://github.com/opentargets/data_pipeline/issues/220

**Comment by LucaFumis** [comment]
For the webapp this is in `components/rare-disease-table/rare-disease-table-directive.js` and has a handy comment `TODO: https://github.com/opentargets/webapp/issues/226`

**Comment by LucaFumis** [comment]
Data issue; still outstanding.
An example can be seen here: https://www.targetvalidation.org/evidence/ENSG00000157764/Orphanet_79364

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #22](https://github.com/opentargets/platform/issues/22) via [**ZenHub**](https://www.zenhub.com/)
