### ISSUE TITLE
add a link to our youtube channel

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#231]
I've just created an Open Targets channel on youtube:

https://www.youtube.com/channel/UCLMrondxbT0DIGx5nGOSYOQ

Can we add a youtube icon on the homepage of our Platform please? From the footer for example?

I would also write a paragraph about this to go to the Outreach page.

There will be more videos uploaded there. We may have almost 10 at the moment.

**Comment by LucaFumis** [comment]
Will do this together with the Medium logo icon

**Comment by LucaFumis** [comment]
Updated as part of issue #232
