### ISSUE TITLE
Searching by microRNA does not work

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#234]
### Observed behaviour
Enter hsa-mir-3607 in the search box.
This returns nothing and does not auto-complete.
The page exist though
https://www.targetvalidation.org/target/ENSG00000284078

### Expected behaviour
Auto-completion works
Search for this microRNA works

### Environment
* Version: production
* Browser: All

**Comment by peatroot** [comment]
Closing and moving to `rest_api`. See https://github.com/opentargets/rest_api/issues/150.
