### ISSUE TITLE
Non-coding RNA target profile page needs to be redesigned

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#235]
### Observed behaviour
For https://www.targetvalidation.org/target/ENSG00000284078
Some sections are irrelevant since it's not a protein-coding gene

### Expected behaviour
Less sections on the target profile page.

### Environment

* Version: production
* Browser: all

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #18](https://github.com/opentargets/platform/issues/18) via [**ZenHub**](https://www.zenhub.com/)
