### ISSUE TITLE
On discarding uploaded target list in disease associations page, target table does not update

### ISSUE THREAD

**Issue by peatroot** [opentargets/webapp#236]
### Observed behaviour
There are over 2000 targets associated with asthma. After uploading a list of 36 targets, the table displays just these 36. However, when the target list is cancelled, the table continues to display 36 targets and does not revert to 2000.

### Expected behaviour
Cancelling target list usage should revert to previous state.

### Environment
* Version: 3.4.4
* Browser: Chrome

**Comment by LucaFumis** [comment]
I can't reproduce this at present: all appears to be working correctly in production. 
Marking as fixed.
