### ISSUE TITLE
Source of mouse phenotypes is MGI not PhenoDigm

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#239]
### Observed behaviour
On the target profile page, it's indicated that the mouse phenotype information comes from PhenoDigm

### Expected behaviour
The source of information should be MGI 
http://www.informatics.jax.org/

### Environment
[How did you see the bug?]
* Version: current 3.4
* Browser: All

**Comment by peatroot** [comment]
Fixed in `master` and production (tag `3.4.7`).
