### ISSUE TITLE
Text Mining Evidence Export: Authors are not exported and 'Carcinoma, Lewis Lung' is split into two columns

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/webapp#241]
### Observed behaviour
1) The author column in the Text Mining Download only has commas (the correct number of commas!) but no names.

disease | publication id | title | authors
-- | -- | -- | --
fibrosis | 28834223 | Liver and systemic hemodynamics in children with cirrhosis: Impact on the   surgical management in pediatric living donor liver transplantation. | , , , , , , , , , , , , ,
neoplasm | 28977813 | [Hearing rehabilitation with the cochlea implant following   translabyrinthine CPA tumor removal ?] | , , ,

2) 'Carcinoma, Lewis Lung' is split into two columns:
disease | publication id | title | authors
Carcinoma | Lewis Lung | 27515027 | Metronomic cyclophosphamide activation of   anti-tumor immunity: tumor model, mouse host, and drug schedule dependence of   gene responses and their upstream regulators. | , ,

### Expected behaviour
1) The author names
2) Lewis Lung Carcinoma in the 'disease' column

### Environment
[How did you see the bug?]
* Version: On the website
* Browser: Safari

**Comment by LucaFumis** [comment]
Now fixed.

**Comment by LucaFumis** [comment]
Fix added to `master` and production `v3.4`
