### ISSUE TITLE
Text Mining Evidence Section: Collapsing/Expanding of sections mixed up if one PMID occurs more than once

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/webapp#242]
### Observed behaviour
On Page 3 of the Text Mining Evidence [here](http://www.targetvalidation.org/evidence/ENSG00000091704/EFO_0000616), PMID 28250426 occurs three times and trying to expand or collapse sections of the non-first entry for this PMID, acts on the previous entry that has the corresponding section, i.e., Abstract is always collapsed for the first entry, Results is always expanded or collapsed for the 2nd entry because it occurs there first.
 
### Expected behaviour
Expanding or collapsing of the section I am trying to expand or collapse.

### Environment
[How did you see the bug?]
* Version: Website
* Browser: Safari

**Comment by LucaFumis** [comment]
This is now fixed - https://textmining-fix--paratrooper-antelope-70721.netlify.com/evidence/ENSG00000091704/EFO_0000616
Will merge and push together with more fixes in the same component.

**Comment by LucaFumis** [comment]
Fix added to `master` and production `v3.4`
