### ISSUE TITLE
Text Mining: Target and Disease not always highlighted

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/webapp#243]
### Observed behaviour
In the text mining section, for papers Nr. 3 and 4 in the list, target and disease are not highlighted in the abstract. Highlighting works fine for other PMIDs.

### Expected behaviour
Target and disease to be highlighted.

### Environment
[How did you see the bug?]
* Version: Website
* Browser: Safari

**Comment by LucaFumis** [comment]
Hi Michaela, 
for which pages (or target/disease combination) did you observe this? Or was it quite quite widespread?
I can replicate it for PTGDR2 in asthma.

**Comment by LucaFumis** [comment]
This seems the same (data issue actually) as issue #240 
Closing - please reopen if unrelated
