### ISSUE TITLE
Text Mining: Year of publication is shown as 1800 instead of 1984

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/webapp#244]
### Observed behaviour
Year of the second publication is 1800 instead of 1984:
http://www.targetvalidation.org/evidence/ENSG00000070031/EFO_0003891

### Expected behaviour
It should be 1984.

### Environment
[How did you see the bug?]
* Version: Website
* Browser: Safari

**Comment by LucaFumis** [comment]
That's how it is in the API response actually:
https://api.opentargets.io/v3/platform/public/evidence/filter?target=ENSG00000070031&disease=EFO_0003891&datasource=europepmc&size=10&from=0&sort=literature.date&search=&draw=1&expandefo=true

literature.date: "1800-01-01"

@ckongEbi might be able to help?

**Comment by emepyc** [comment]
That date is the default for "no date available". I suppose that is more a
data problem than UI, unless you want to substitute that date for "Not
available" or something like that. At least, being it a real date doesn't
break sorting etc

**Comment by peatroot** [comment]
This should be handled at `rest_api` level or earlier. Moving to https://github.com/opentargets/data_pipeline/issues/248.
