### ISSUE TITLE
Text Mining: Title is not shown completely in Text Mining evidence section

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/webapp#245]
### Observed behaviour
Title of the 3rd paper (http://www.targetvalidation.org/evidence/ENSG00000124557/HP_0000118) is shown as "Altered expression of Butyrophilin (" instead of "Altered expression of Butyrophilin (BTN) and BTN-like (BTNL) genes in intestinal inflammation and colon cancer."

### Expected behaviour
See above.

### Environment
[How did you see the bug?]
* Version: Website
* Browser: Safari

**Comment by ckongEbi** [comment]
looks like a split command on "(" causing this...

**Comment by LucaFumis** [comment]
Also here it's from the API response, in `literature.title`:
```
"literature": {
"doi": null,
"title": "Altered expression of Butyrophilin (",
```
While it looks OK in `evidence.literature_ref.mined_sentences[].text`

**Comment by LucaFumis** [comment]
Closing and moving issue to `data_pipeline`: https://github.com/opentargets/data_pipeline/issues/251
