### ISSUE TITLE
Add description to 'Bibliography' section on Disease ad Target Profiles

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/webapp#250]
Add description to 'Bibliography' section on Disease and Target Profiles to say that Bibliography info comes from Open Targets Library.

**Comment by LucaFumis** [comment]
Do we have the text? Or maybe @MichaelaEBI or @deniseOme you have something already written down?
Low priority, so no rush

**Comment by deniseOme** [comment]
Hi @LucaFumis, sorry I have missed this ticket. 

We could have:
Scientific literature on **BRAF** from LINK, the Open Targets Literature Knowledge Graph (http://blog.opentargets.org/2018/01/18/link/)

**Comment by LucaFumis** [comment]
Thank you @deniseOme and @MichaelaEBI. Now fixed in commit edb443c
