### ISSUE TITLE
drug with no mechanism of action 

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#252]
This drug has no mechanism of action: http://www.targetvalidation.org/summary?drug=CHEMBL2104708

### Observed behaviour
However under the "Mechanism of action" section in the drug page, there is a wheel that keeps spinning suggesting there is data to be loaded.

![screen shot 2018-02-22 at 14 47 02](https://user-images.githubusercontent.com/6472381/36557571-8af2cb6e-1800-11e8-9a42-087babcc62f0.png)

### Expected behaviour
I expected the page to load with an empty field under Mechanism of action. Similar to what is shown for "Targets associated with MELDONIUM" and "Diseases associated with MELDONIUM".

<img width="532" alt="screen shot 2018-02-22 at 18 49 44" src="https://user-images.githubusercontent.com/6472381/36557674-d6a01954-1800-11e8-96e5-a06f64a2f4e2.png">

### Environment
* Version: 3.4.8
* Browser: Chrome

**Comment by LucaFumis** [comment]
Thanks Denise.
This was actually fixed shortly before you filed the issue, as previously noticed by Miguel -  https://github.com/opentargets/webapp/issues/207 - but it might have been pushed to production only with the latest release.
Looking at your example http://www.targetvalidation.org/summary?drug=CHEMBL2104708 it seems to work as expected now (i.e. not showing content for the mechanism of action tab).

**Comment by deniseOme** [comment]
Thank you!
Good to see no more spinning wheel.
