### ISSUE TITLE
in batch search we expect autocomplete and not search

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#255]
@emepyc commented on [Tue Jan 17 2017](https://github.com/opentargets/rest_api/issues/39)

http://targetvalidation.org/search?src=q:TAS2R43

This gives as first result rtp3 because tas2r43 doesn't have associated diseases, but in the context of batch search that looks like a mapping error

---

@elipapa commented on [Wed Jan 18 2017](https://github.com/opentargets/rest_api/issues/39#issuecomment-273533770)

along the same lines of #38 

---

@elipapa commented on [Mon Nov 13 2017](https://github.com/opentargets/rest_api/issues/39#issuecomment-343912881)

perhaps we should have a "lookup" method as suggested in #57

**Comment by elipapa** [comment]
i think a better lookup API is already available:

http://mygene.info/trydemo/

batch search should have a lookup, not use the search method

**Comment by LucaFumis** [comment]
This should be an API/backend so marking as "won't fix" for now

**Comment by LucaFumis** [comment]
Am I getting confused, or has @mkarmona fixed this in the back end last week?

**Comment by elipapa** [comment]
it has been patched, yes. A more complete rewrite and design of the search will be necessary, as there are different functions we use one function for:
- autocomplete
-search
-symbol lookup

Ideally these should be separate. Not a webapp problem, at least until we implement it in the API.
