### ISSUE TITLE
Update search API calls to use search_entities=target where relevant

### ISSUE THREAD

**Issue by peatroot** [opentargets/webapp#256]
The REST API has a breaking change as a result of fixing the search functionality. The endpoints `/v3/platform/public/search`, `/v3/platform/private/quicksearch` and `/v3/platform/private/besthitsearch` should add the key/value `search_entities=target` to such calls.

**Note**: This is only relevant to searches with key/value `filters=target` already (which affects `otTargetListMapping`, `otTargetListUpload`, `otInteractionsViewer`, `otFilterByFileTargets`, `otDrugSummary`)

**Comment by peatroot** [comment]
@mkarmona @elipapa, can you confirm that the above is where this change should be applied?

**Comment by elipapa** [comment]
![image](https://user-images.githubusercontent.com/112610/37036631-2a4c42c6-2148-11e8-9d56-d9505e57af55.png)
all these calls should be to `besthitsearch` and should contain the `search_entities=target` parameter, which makes `besthitsearch` behave more like a `lookup`

**Comment by elipapa** [comment]
![image](https://user-images.githubusercontent.com/112610/37036763-83a71fda-2148-11e8-8c27-1929ed2d7cd9.png)
also here, because he is using `besthitsearch` as a lookup

**Comment by elipapa** [comment]
after @peatroot and I walked through it:

* you should pass the `search_entities=target` parameter when using besthitsearch only, iff `filters=target` already
* you should change the batchSearch page to only use `besthitsearch` also when trying to map "suggested matches"

**Comment by elipapa** [comment]
the above applies to the drug entity page as well
![image](https://user-images.githubusercontent.com/112610/37038376-8be086b0-214c-11e8-836f-a03538b2ef4e.png)

however, here the `search` calls should remain `search` calls, but should have the parameter `search_entities=drugs` added to the call as well.

**Comment by peatroot** [comment]
When trying to apply the change to the protein interactions viewer, the updated API call with `search_entities=target` returns `null` for queries involving Uniprot IDs, so excluding this in patch.

**Request**: `besthitsearch` with payload
```
{"q":["P15056","Q15118","P01137","P10398","P61981","O14744","P27361","Q04917","P62834","Q06323","Q92918","Q8IVT5","P61224","P31946","P51817","P01116","Q05639","P47736","P46940","P17612","Q96BR1","O14807","Q9HBY8","Q3ZCQ8","P33981","O43482","O43930","P31749","P06400","P17252","P63104","P04049","P31947","P68104","Q02750","P01111","P28482","P36507","P49841","P01112","P31751","O00141","Q13177","Q13153","Q9Y243","P27348","Q15382","P30086","Q92934"],"filter":"target","search_entities":"target","fields":["approved_symbol","association_counts","ensembl_gene_id"]}
```
**Response**:
```
{"data_version": "18.02", "data": [{"q": "P15056", "id": null}, {"q": "Q15118", "id": null}, {"q": "P01137", "id": null}, {"q": "P10398", "id": null}, {"q": "P61981", "id": null}, {"q": "O14744", "id": null}, {"q": "P27361", "id": null}, {"q": "Q04917", "id": null}, {"q": "P62834", "id": null}, {"q": "Q06323", "id": null}, {"q": "Q92918", "id": null}, {"q": "Q8IVT5", "id": null}, {"q": "P61224", "id": null}, {"q": "P31946", "id": null}, {"q": "P51817", "id": null}, {"q": "P01116", "id": null}, {"q": "Q05639", "id": null}, {"q": "P47736", "id": null}, {"q": "P46940", "id": null}, {"q": "P17612", "id": null}, {"q": "Q96BR1", "id": null}, {"q": "O14807", "id": null}, {"q": "Q9HBY8", "id": null}, {"q": "Q3ZCQ8", "id": null}, {"q": "P33981", "id": null}, {"q": "O43482", "id": null}, {"q": "O43930", "id": null}, {"q": "P31749", "id": null}, {"q": "P06400", "id": null}, {"q": "P17252", "id": null}, {"q": "P63104", "id": null}, {"q": "P04049", "id": null}, {"q": "P31947", "id": null}, {"q": "P68104", "id": null}, {"q": "Q02750", "id": null}, {"q": "P01111", "id": null}, {"q": "P28482", "id": null}, {"q": "P36507", "id": null}, {"q": "P49841", "id": null}, {"q": "P01112", "id": null}, {"q": "P31751", "id": null}, {"q": "O00141", "id": null}, {"q": "Q13177", "id": null}, {"q": "Q13153", "id": null}, {"q": "Q9Y243", "id": null}, {"q": "P27348", "id": null}, {"q": "Q15382", "id": null}, {"q": "P30086", "id": null}, {"q": "Q92934", "id": null}]}
```

**Comment by peatroot** [comment]
Tried switching batch search **Add more targets to your list** call from using `search` to `besthitsearch` as suggested.

When I tried searching for `BRAF` using `besthitsearch` (with or without presence of `search_entities=target`), `BRAF` is not the top listed result, which seems wrong.

<img width="132" alt="screen shot 2018-03-06 at 16 05 18" src="https://user-images.githubusercontent.com/7376272/37043460-941b93b8-2158-11e8-85c3-d190c9d6a891.png">

**Comment by peatroot** [comment]
Full set of usages of search in `webapp`:

# Uses of otApi.getSearch
| Code Location | Page(s) where relevant | Type | Params | 
| -- | -- | -- | -- |
| otTargetListMapping | Batch search | GET | {q:<user uploaded gene>, filter: 'target', size: 10, fields: 'approved_symbol'} |
| otDrugSummary | Drug summary | GET | {q:<drugName>, filter: 'target', size: 100} |
| otDrugSummary | Drug summary | GET | {q:<drugName>, filter: 'disease', size: 100} |
| SearchController.getFiltersData | Search results | GET | {q:<user query>, filter: <page dependent, I think>, size: 0} |
| SearchController.getResults | Search results | GET | {q:<user query>, filter: <page dependent, I think>} |

# Uses of otApi.getBestHitSearch
| Code Location | Page(s) where relevant | Type | Params | 
| -- | -- | -- | -- |
| otInteractionsViewer | Target profile | POST | {q:<uniprot ids>, filter: 'target', fields: ['approved_symbol', 'association_counts', 'ensembl_gene_id']} |
| otTargetListUpload | Batch search | POST | {q:<user uploaded genes>, filter: 'target', fields: 'approved_symbol'} |
| otDrugAdverseEventsDirective | Drug summary | POST | {q:<events>, filter: 'disease', fields: ['efo_code', 'efo_label']} |
| otDrugSummary | Drug summary | POST | {q:<gene synonym list>, filter: 'target'} |
| otFilterByFileTargets | Disease associations | POST | {q:<user uploaded genes>, filter: 'target', fields: 'approved_symbol'} |

# Uses of otApi.getQuickSearch
| Code Location | Page(s) where relevant | Type | Params | 
| -- | -- | -- | -- |
| SearchBoxController | Search prompt | GET | {q:<user query>, size: 3} |

**Comment by elipapa** [comment]
updated the table above
