### ISSUE TITLE
PMID:23193172 not hyperlinked in description of targets (profile page)

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#259]
### Observed behaviour
The PubMed IDs are hyperlinked in UniProt (http://www.uniprot.org/uniprot/P00813) but not in Open Targets (https://www.targetvalidation.org/target/ENSG00000196839)

### Expected behaviour
IDs to be hyperlinked and pointing to somewhere. Europe PMC (to be consistent with other link outs re. papers)? Or PubMed as the ID says PubMed:23193172.

Or could we have PMID:23193172 and point to Europe PMC?

### Environment
* Version: 3.5.5
* Browser: Chrome

Thanks.
Denise

**Comment by LucaFumis** [comment]
We can implement something in javascript, front end side. 
But matching strings like this might not to be a robust solution, leading to errors and ill looking content.
Ideally we'd get a marked up content from the API...

**Comment by LucaFumis** [comment]
Tried this as bit of fun; will be included in next candidate release for testing.
