### ISSUE TITLE
add to drug indication to batch search drug table

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#260]
### Why?
Drug indications are not included in the current table
![image](https://user-images.githubusercontent.com/112610/37335067-748e13fc-26a5-11e8-99fb-023cb639d2bf.png)
and it would be an important addition to judge what compounds are in the space.

@andrewhercules this is a suggestion from @MayaGhoussaini

The data is available but not displayed.

**Comment by andrewhercules** [comment]
I'll add this as a front-end priority for 18.04 as part of my drug table summary redesign project that was inspired by feedback from @gkos-bio. Related to this, I spoke with @MayaGhoussaini and she also mentioned it would be good to have the primary target information on the drugs table in the target profile page.
