### ISSUE TITLE
Move filtering tabs from the bottom to the top of the table

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#264]
### Observed behaviour
Filtering functionality in tables in the Evidence page as well as Target profile can be missed (go unnoticed) as the button is placed at the bottom of the table.

e.g.
http://www.targetvalidation.org/evidence/ENSG00000157764/EFO_0003777?view=sec:genetic_association

### Expected behaviour
Filtering functionality would be more useful if placed at the top of the table. Easier for users to spot it. They would not need to scroll down to see it. It's already up there when they first see the columns.

<img width="1026" alt="screen shot 2018-03-21 at 20 54 07" src="https://user-images.githubusercontent.com/6472381/37736821-d92fb734-2d49-11e8-94b5-9834e78a96a1.png">

<img width="869" alt="screen shot 2018-03-21 at 20 56 53" src="https://user-images.githubusercontent.com/6472381/37736823-dbeaadc6-2d49-11e8-8402-21533f7b0e30.png">

**Comment by LucaFumis** [comment]
This came up also in the drugs table revamp; here's a quick hacked version - look at the drugs table:
https://tablefiltersfix--paratrooper-antelope-70721.netlify.com/target/ENSG00000157764
If it's good I'll roll it over to the other tables (each table html has to be manually updated :/ )

**Comment by LucaFumis** [comment]
This is now fixed in production.
