### ISSUE TITLE
We link out to clinicaltrials.gov but the target information comes from ChEMBL not clinical trials.

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#265]
### Observed behaviour
When we display drug information in the evidence page and profile pages we link out to clinicaltrials.gov. Although that shows the trial ID e.g. NCT02187055 which is useful, biologists would like to go to the original source and see the gene (target) in that page. This is not the case as the curation is done by ChEMBL and the target is not listed in the clinical trial file:

e.g.

We link one of the drug entries from this target profile page (https://www.targetvalidation.org/target/ENSG00000105397) to its clinical trial record (https://clinicaltrials.gov/search?id=%22NCT02187055%22), column named as evidence source.

However in the clinical trials page, there is no mention of ENSG00000105397 or TYK2.

### Expected behaviour
Biologists would like to review the clinical trial and the mention of the target (in this example ENSG00000105397 or TYK2).

Same applies to the ATC records.

Although the original source is the clinicaltrial.gov, the target name is not there.

We do provide links that could take the user to the original target info (https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL221959 or http://chembl.blogspot.co.uk/search?q=TOFACITINIB) but with so many links in that table, a user may not find what they are looking for, they can become frustrated and therefore never come back to the Platform (Eric Lightcap's own words).

 As this info comes from ChEMBL, shouldn't we link out to ChEMBL. They do link out to clinical trials from their page. So if users want to get to the NCT ID they will get there via ChEMBL.

### Environment
[How did you see the bug?]
* Version: [eg. 3.4.1 (for production) or the url (if a development branch)]
* Browser: [Chrome | Firefox | IE | Safari ...]

**Comment by LucaFumis** [comment]
Hi Denise,
those links to clinicaltrials or dailymed come back like that from the API.
Could you tell me, say for the examples above, what the correct alternative link to ChEMBL would be (or look like) please?
Cheers,
L

**Comment by andrewhercules** [comment]
I'm closing this ticket as the API response provides links to ClinicalTrials, ATC, and DailyMed, which have been curated by ChEMBL. Changing the table and directing users to the ChEMBL site would increase the overall cost of interaction, despite giving users the same information they can get from the current table.

I've flagged this to @MichaelaEBI and she will consider this as we look at implementing a drug entity within the Platform.
