### ISSUE TITLE
Can't download the images from DoRothEA

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#266]
### Observed behaviour
I tried to download an image and although I get a file, there is no image in it.

This is for all scenarios: 
a) no filtering (as above),
b) filtering by drug (http://dorothea.opentargets.io/#/investigation/1?filterInteractionsBy=drug&filterInteractionsOnDrug=3)

<img width="1237" alt="screen shot 2018-03-21 at 21 23 09" src="https://user-images.githubusercontent.com/6472381/37738009-7e70a0b6-2d4d-11e8-8491-f19355c8e91c.png">

c) filtering by TF
<img width="1222" alt="screen shot 2018-03-21 at 21 26 17" src="https://user-images.githubusercontent.com/6472381/37738116-ea62768c-2d4d-11e8-9e4f-88997ec7b61d.png">

![associations_all-tp53](https://user-images.githubusercontent.com/6472381/37738122-ed1f6aa6-2d4d-11e8-8857-1106c27513a9.png)

### Expected behaviour
I'd expect to get a file with the same image as seen on the website.

### Environment
Version 0.0.23
Chrome

**Comment by andrewhercules** [comment]
Moving this issue to the [dorothea repo](https://github.com/opentargets/dorothea)

**Comment by andrewhercules** [comment]
Issue moved to [opentargets/dorothea #14](https://github.com/opentargets/dorothea/issues/14) via [**ZenHub**](https://www.zenhub.com/)
