### ISSUE TITLE
Batch search "Pathways" CSV download doesn't have full pathway name

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/webapp#271]
### Observed behaviour
After running a batch search, a user downloads the CSV file of the "Pathways" data. However, the full pathway name is not visible. Instead, the name is truncated with ellipsis points (...). See screenshots below for an example:

![screen shot 2018-04-13 at 10 13 04](https://user-images.githubusercontent.com/7490258/38726993-acb2fb32-3f03-11e8-9609-1f08904d1517.png)

![screen shot 2018-04-13 at 10 13 18](https://user-images.githubusercontent.com/7490258/38727014-bd927612-3f03-11e8-8eb6-a8abc54fc52c.png)

### Expected behaviour
Users expect the entire full pathway name to be visible so that they can further analyse pathways of interest. This can be achieved using the same functionality found when a user runs a batch search and downloads the "Diseases associated" CSV file. In this CSV file, there is a column called "Disease full name" which provides the full name of all diseases, regardless of whether they have been truncated with ellipsis points. See below for a screenshot:

![screen shot 2018-04-13 at 10 17 40](https://user-images.githubusercontent.com/7490258/38727086-f01e2284-3f03-11e8-9395-d23ba3beaa3b.png)

### Environment
* Version: 3.5.10
* Browser: Chrome, Firefox
* Other software: MS Excel

**Comment by deniseOme** [comment]
Reported by user as well on the 24th April, by IBM users in Japan.

![screen shot 2018-05-10 at 11 56 51](https://user-images.githubusercontent.com/6472381/39866651-626cbb0c-5449-11e8-95f8-b031d29f7511.png)

**Comment by LucaFumis** [comment]
Long pathways names should be truncated with CSS (to preserve full name, which should be reflected in the download).

**Comment by LucaFumis** [comment]
This is now fixed in production.
