### ISSUE TITLE
bubbles don't get adjusted besides filter applied

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#276]
### Observed behaviour
User from Biogen reported that when searching for DPYSL2, navigating to its associated diseases and selecting Genetic associations only, there was no change in the Bubbles view or Tree view.

The Table view works as expected: when Genetic associations filter is applied, the number of rows change accordingly.

Note: the other Data types behaviour is as expected: reduces the number of diseases displayed as bubbles and lines in the tree

### Expected behaviour
There is one disease associated with DPYSL2 when associations are filtered based on the Genetic asssociations only. So we would expect one bubble only (or one line only in the Tree view).

### Environment
[How did you see the bug?]
* Version: [3.6.1]
* Browser: Google Chrome and Firefox

![screen shot 2018-05-15 at 13 54 28](https://user-images.githubusercontent.com/6472381/40057924-8893807a-5847-11e8-9419-30618e73421c.png)

**Comment by emepyc** [comment]
It seems a data problem (or API, if the API has been changed recently).
The API response is expected to include a top level `therapeutic_areas` property:

https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000092964&size=10&direct=true&facets=false&datatype=genetic_association

but when selecting the `genetics_associations` in the response to the resulting API call that property is missing:

https://api.opentargets.io/v3/platform/public/association/filter?target=ENSG00000092964&size=10&direct=true&facets=false&datatype=genetic_association

@mkarmona?

**Comment by andrewhercules** [comment]
Question for @emepyc, @peatroot, or @LucaFumis ... is the Bubbles view able to render a therapeutic area where there are no child elements to be rendered? In other words, an empty circle? 

In the case of DPYSL2, when filtering by `Data Type --> Genetic Associations`, the associated disease is `genetic disorder`, which is a parent therapeutic area. So in theory, the Bubbles View should show a white circle with a black border with a `genetic disorder` label, but no children - see below for a low-fidelity mockup. Is this possible? 

![genetics-assoc](https://user-images.githubusercontent.com/7490258/40061169-3ac7a6ba-5850-11e8-8c24-5224395d937d.png)

**Comment by emepyc** [comment]
The widget expects always at least a disease and a therapeutic area.
Even in cases where the disease == therapeutic area, the expectation is that the API response includes "genetic disorder" as the disease and "genetic_disorder" as the therapeutic area, which _should_ result in a therapeutic area outer circle and a disease inner circle, both having the same name.

**Comment by andrewhercules** [comment]
Issue moved to data_pipeline repository as API returns `disease` and `therapeutic_areas` attributes for other associations.

**Comment by andrewhercules** [comment]
Issue moved to [opentargets/data_pipeline #296](https://github.com/opentargets/data_pipeline/issues/296) via [**ZenHub**](https://www.zenhub.com/)
