### ISSUE TITLE
Facets: selecting child checkbox keeps parent selected

### ISSUE THREAD

**Issue by LucaFumis** [opentargets/webapp#277]
### Observed behaviour
Target association page for BRAF, select 'Genetic Associations' under datatypes.
Now expand the Genetic associations facet via the little caret on the right: this displays the datasources for genetic association.
Select 'uniprot' (or any other).
The data doesn't change. The URL still shows the datatype as selected.
This seems to be longstanding.

### Expected behaviour
Selecting a child facet should deselect the parent facet (at least for datatypes), as parent data encompasses children data.
If for some reason this is not possible, then a user should not be able to select child filter if parent is selected

### Environment
* Version: 3.6.2
* Browser: Chrome, any

**Comment by LucaFumis** [comment]
I had started looking into this but the facets code is non-trivial and will need to spend a little more time on it.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #17](https://github.com/opentargets/platform/issues/17) via [**ZenHub**](https://www.zenhub.com/)
