### ISSUE TITLE
replace API calls for the text mining abstracts with NCBI/europePMC

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#278]
## What is the new feature you are requesting?
Currently we call the api.opentargets.io API to get abstracts in the evidence page:

https://api.opentargets.io/v3/platform/public/evidence/filter?target=ENSG00000157764&disease=EFO_0000701&datasource=europepmc&size=10&from=0&sort=literature.date&search=&draw=1&expandefo=true

![image](https://user-images.githubusercontent.com/112610/40110034-e4f76d9a-58f6-11e8-8f8f-d93e7871240c.png)

This is very fast but requires the backend to keep up the literature pipeline. Albeit slower, it makes more engineering sense to outsource that to a _literature_ API. 

We would like to phase out abstracts from the data pipeline.

Two options:

- europePMC
_(no POST method, ugly query, more flaky, but comes back in JSON)_
https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=ext_id%3A21791085%20OR%20ext_id%3A22858672%20OR%20ext_id%3A25395120&format=json&resultType=core

- NCBI eUtils
_(has a POST method, but comes back in XML)_
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=10173216%2C11910682%2C10371555&retmode=xml&rettype=abstract&api_key=2ca809aa534e61185d8e3a433b230b992608

Benchmarks:

![image](https://user-images.githubusercontent.com/112610/40110395-c66211c2-58f7-11e8-93a1-40cb9e3edda3.png)

## Origin of request
Mostly to simplify managing literature as part of the data_pipeline. Please see https://docs.google.com/document/d/1eo2YXJCEdvbckjOqUo9fnmkZOBKtQEsq8MivhF7oU8k/edit#heading=h.9zods4j80kd7 for more details

**Comment by ckongEbi** [comment]
```
{"type":"literature","sourceID":"europepmc","target":{"activity":"http://identifiers.org/cttv.activity/up_or_down","id":"http://identifiers.org/uniprot/P25713","target_type":"http://identifiers.org/cttv.target/protein_evidence"},"disease":{"id":"http://www.orpha.net/ORDO/Orphanet_3389","name":"tuberculosis"},"evidence":{"unique_experiment_reference":"http://europepmc.org/abstract/MED/330","resource_score":{"type":"summed_total","value":14.2,"method":{"description":"Custom text-mining method for target-disease association"}},"literature_ref":{"lit_id":"http://europepmc.org/abstract/MED/330","mined_sentences":[{"section":"title","t_start":70,"t_end":93,"d_start":206,"d_end":217,"text":"Conditions for production, and some characteristics, of mycobacterial growth inhibitory factor produced by spleen cells from mice immunized with viable cells of the attenuated H37Ra strain of Mycobacterium tuberculosis."}]},"provenance_type":{"database":{"version":"2018-04-04","id":"EuropePMC"}},"is_associated":true,"date_asserted":"1975-10-01T00:00:00Z","evidence_codes":["http://www.targetvalidation.org/evidence/literature_mining","http://purl.obolibrary.org/obo/ECO_0000213"]},"validated_against_schema_version":"1.2.8","access_level":"public","unique_association_fields":{"target":"http://identifiers.org/uniprot/P25713","publicationIDs":"http://europepmc.org/abstract/MED/330","disease_uri":"http://www.orpha.net/ORDO/Orphanet_3389"},"literature":{"references":[{"lit_id":"http://europepmc.org/abstract/MED/330"}]}}
```
example of epmc evidence line

**Comment by andrewhercules** [comment]
@LucaFumis, can we also add a column with just the PubMed IDs? That way if someone downloads the file to use the PubMed IDs in their pipeline, they don't need to do any post-processing with the URL to obtain the PubMed ID.

**Comment by elipapa** [comment]
we could do some processing with the API, however that is how we receive
the evidence from europePMC.

**Comment by LucaFumis** [comment]
The current download function for text mining is different than from other tables: we manually process and convert the json to csv (normally Datatables does this).
That's not too bad actually: just join the arrays with commas and new lines.
So if we want to include the pmid on its own we just get the API response as json and process it.

The `format=tab` option returns a *tab* separated values file, so we can save it as `.tsv` instead of `.csv` and all works fine in Excel.

Actually in processing the download data, we currently also wrap everything in quotation marks to avoid commas in the content messing up csv structure.

**Comment by LucaFumis** [comment]
Merged into master and production
