### ISSUE TITLE
Broken external links in the "Mechanism of Action" column in evidence page drugs tables

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/webapp#286]
### Observed behaviour
In the Mechanism of Action column in the known drugs table, the external links do not work if there are both publications and non-publications links. 

For example, on the [CACNA1B in asthma evidence page](https://www.targetvalidation.org/evidence/ENSG00000148408/EFO_0000270?view=sec:known_drug), the `ISBN` link is `http://europepmc.org/abstract/MED/18299583,http://www.accessdata.fda.gov/drugsatfda_docs/label/2012/022544s008lbl.pdf,http://www.isbnsearch.org/isbn/0121844536,http://en.wikipedia.org/wiki/Gabapentin`, a comma-separated list of all the external links that the API returns. Instead, it should just be `http://www.isbnsearch.org/isbn/0121844536`. See below for a screenshot of the issue.

![screen shot 2018-06-04 at 11 33 10](https://user-images.githubusercontent.com/7490258/40913534-cbb06526-67ec-11e8-9698-af9dbf545880.png)

The same issue can be found on other evidence pages including [BRAF and lung carcinoma](https://www.targetvalidation.org/evidence/ENSG00000157764/EFO_0001071?view=sec:known_drug) and [KDR and liver disease](https://www.targetvalidation.org/evidence/ENSG00000128052/EFO_0001421?view=sec:known_drug). The issue can also be found on target profile pages (e.g. [KCNQ3](https://www.targetvalidation.org/target/ENSG00000184156)) and disease profile pages (e.g. [liver disease](https://www.targetvalidation.org/disease/EFO_0001421)).

### Expected behaviour
The links should be properly formatted so that only one link appears per external link reference. So taking the above example of [CACNA1B in asthma evidence page](https://www.targetvalidation.org/evidence/ENSG00000148408/EFO_0000270?view=sec:known_drug), in the Mechanism of Action column, there should be the following links:

[1 publication](http://europepmc.org/abstract/MED/18299583)
[FDA](http://www.accessdata.fda.gov/drugsatfda_docs/label/2012/022544s008lbl.pdf)
[ISBN](http://www.isbnsearch.org/isbn/0121844536)
[Wikipedia](http://en.wikipedia.org/wiki/Gabapentin)

### Environment
* Version: 3.6.11
* Browser: Chrome, Firefox

**Comment by LucaFumis** [comment]
This needs to be fixed at data level / API first. Splitting the string on commas is not a big problem but must have corresponding `nice_name`s. 
Ideally we have *one link only* per `url` array item.

**Comment by andrewhercules** [comment]
Thanks @LucaFumis. I'll close the issue here and copy it to the `data_pipeline` repo.

**Comment by andrewhercules** [comment]
Issue moved to [opentargets/data_pipeline #288](https://github.com/opentargets/data_pipeline/issues/288) via [**ZenHub**](https://www.zenhub.com/)
