### ISSUE TITLE
Batch search - exact protein name matches but still 'offers suggested matches'

### ISSUE THREAD

**Issue by MichaelaEBI** [opentargets/webapp#287]
### Observed behaviour
In a batch search of 133 proteins, CD27 & MYO1G had suggested matches even though there are exact matches for these two proteins.

### Expected behaviour
These two proteins to appear in the 'Exact matches' box.

### Environment
[How did you see the bug?]
* Version: online
* Browser: Safari

**Comment by MichaelaEBI** [comment]
I just chatted with him on Slack - I did a batch search with 133 proteins and observed this behaviour again. Miguel will look into this on Friday.

**Comment by deniseOme** [comment]
Even if you do a batch search with the two offending gene symbols, the expected behaviour won't be observed.

Good to know the bug is back, in case users report the same. Is it worth merging this with the previous ticket?

**Comment by deniseOme** [comment]
#274 #134

**Comment by MichaelaEBI** [comment]
Denise, yes, please feel free to merge with previous ticket - I did not find #134 yesterday.

**Comment by MichaelaEBI** [comment]
Another search with nearly 200 proteins today revealed that these two also result in suggested matches even though there are exact matches: PRMT5 & FGFR1. For PRMT5 there are the following three suggestions in addition to PRMT5:
- COPRS
- PRMT5-AS1
- PRMT5P1
The last two will be suggestions based on name and the first one is a suggestion based on its approved name: [coordinator of PRMT5 and differentiation stimulator](https://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=HGNC:28848)
I don't know how the batch search works, but I think that there should be no need to search any further if there are exact matches.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #24](https://github.com/opentargets/platform/issues/24) via [**ZenHub**](https://www.zenhub.com/)
