### ISSUE TITLE
Target association page - issue sorting disease column by alphabetical order

### ISSUE THREAD

**Issue by andrewhercules** [opentargets/webapp#294]
### Observed behaviour
A user mentioned that when sorting the `Disease` column on the target association page, the sorting is done by alphabetical order, but is not case insensitive. Diseases that begin with capital letters will be found at the top of the list, even if the disease name starts with a "Z".

List found on initial loading of the associations page for [ADAM33](https://www.targetvalidation.org/target/ENSG00000149451/associations):

![screen shot 2018-07-11 at 12 20 46](https://user-images.githubusercontent.com/7490258/42568414-f0652070-8504-11e8-804d-9e96437fc86e.png)

List found on the associations page for ADAM33 after clicking the `Disease` label to sort the disease column: 

![screen shot 2018-07-11 at 12 21 05](https://user-images.githubusercontent.com/7490258/42568473-2ada3790-8505-11e8-9303-7881fab6e592.png)

### Expected behaviour

Users would like to be able to sort the `Disease` column and see the list sorted alphabetically and case insensitive so that "asthma" and "Asthma, child onset" would be treated the same and would appear one after the other in the list.

### Environment
[How did you see the bug?]
* Version: 3.7.2
* Browser: Chrome, Firefox, Safari

**Comment by andrewhercules** [comment]
### Initial triage notes

I spoke to @MichaelaEBI and the disease names we obtain from EFO are inconsistent when it comes to capitalisation. Some have capitals, others do not. For example, the word `acute` is capitalised in [`Acute Leukemia`](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_1000068) whereas it is not capitalised in [`acute hypotension`](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002497).

Not sure if the associations page is using DataTables but if it does, [the default in the current version is to sort case insensitive](https://datatables.net/forums/discussion/38495/not-case-sensitive-ordering-while-client-side-sort-filter-by-column-header). @LucaFumis, could you please look into this?

**Comment by LucaFumis** [comment]
The heat maps on the association pages do indeed use DataTables. However, pagination and sorting is done server-side at API level.
Trying to re-sort the result client side would be unreliable: this only works if all the results are displayed in one screen (i.e. there is no pagination).
Marking as won't fix - this should be addressed in the API.

**Comment by andrewhercules** [comment]
Issued closed as per Luca's comments above
