### ISSUE TITLE
odd behaviour on the search results for "Intellectual disability, mild"

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#295]
### Observed behaviour
When searching for "Intellectual disability, mild" I get a grey page or/and drop down from right hand search bar.

<img width="1012" alt="screen shot 2018-07-24 at 12 22 16" src="https://user-images.githubusercontent.com/6472381/43141394-afbc8c86-8f4d-11e8-94cb-13c1e4272ccd.png">

http://www.targetvalidation.org/search?src=q:Intellectual%20disability,%20mild

I guess the "," is causing this i.e. 
### Expected behaviour
A page returning results similar to what we get when searching for "Intellectual disability" only; without the ", mild" bit.

### Environment
* Version: 3.7.3
* Browser: [Chrome | Firefox ]

**Comment by LucaFumis** [comment]
The issue was indeed caused by the comma "," because the same character is used in the syntax of the URL-encoded state. We decided the best solution was to simply strip any commas from the search string.

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #16](https://github.com/opentargets/platform/issues/16) via [**ZenHub**](https://www.zenhub.com/)
