### ISSUE TITLE
Rendering issue of expression range "  0.0 Ãƒâ€” 100" in the expression widget on IE11

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#31]
Shows:
0.0 Ãƒâ€” 100
should be:
0.0 Ã— 100
looks like the 'x' sign is not converted properly on not using an html code

**Comment by emepyc** [comment]
@gkos-bio can you please confirm this is still happening in the new version of the widget?

**Comment by emepyc** [comment]
@gkos-bio, I'm closing this issue since I can't replicate
