### ISSUE TITLE
Target Profile page: bibliography

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#32]
On the Target profile page of BRAF, under Bibliography, we say there are 35 citations from UniProt and we display 25.

It seems we've got 40 in UniProt instead: http://www.uniprot.org/uniprot/P15056#publications

If the source for this data is UniProt, why do the numbers disagree? Out of sync? To avoid this happening, do we need to say the total number of articles?
 
Perhaps have: "These are some of the publications for BRAF. Check the Publication section of UniProt for the complete list of available articles" and link out.

If we get this from UniProt while do we link to Europe PMC?
Or do we actually get it from Europe PMC? I seem to have heard both answers....

**Comment by elipapa** [comment]
out of date, now that we have a new bibliography
