### ISSUE TITLE
Searching for multiple words (i.e. with spaces)

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#36]
Searching for multiple words (i.e. a string with spaces, for example "Muscular dystrophy") works for the first page of results.
When paginating thorough results, after 2 pages the space in the query string becomes corrupted and the search no longer works.
This almost certainly caused by the app URL-encoding the query string.

**Comment by LucaFumis** [comment]
We're talking about the main search, right? Not a search within a table or heatmap.
Pretty sure I've fixed / worked on this a while ago: looking in production it appears to work OK.

Can mark this is done or close.

**Comment by emepyc** [comment]
Yes, this was fixed a while ago.
Please reopen if needed.
