### ISSUE TITLE
some information on the non-coding nature of lncRNA (and other non-coding) genes

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#41]
While putting a tip on open targets facebook on this paper

http://www.nature.com/nsmb/journal/v20/n7/full/nsmb.2591.html

It occurred to me that it may be helpful to include some sort of message for targets that are non-coding genes e.g. HOTAIR: 

https://www.targetvalidation.org/target/ENSG00000228630

The message in Protein Baseline Expression (and Gene Ontology) would not apply for ncRNA genes (or the lncRNA that seem to be associated with diseases).

Whereas the messages in Protein structure (perhaps Reactome too) can be dubious as we get that message sometimes in genes that are coding but are not known to have PDBe or pathways...But if we had 'this is a non-coding gene so no protein structure is expected' (or something similar), it could be more informative to users...

**Comment by andrewhercules** [comment]
Ticket closed as we cannot alter the various third-party plugins and widgets used by the Platform. However, I've noted this as a feature request if we moved to more of a dashboard view. Perhaps we could make it clearer to users that the gene is non-coding and present a different dashboard view that only displays the widgets relevant for non-coding genes.
