### ISSUE TITLE
scoring heatmap bar

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#43]
The legend of the score does range from light blue (0) to dark blue (1). However 0 should be white, not light blue. It could be slightly misleading for someone who has a keen eye to details.

**Comment by andrewhercules** [comment]
Ticket closed as heat map legend shows an white box with grey border as 0 - see below:

![screen shot 2018-06-28 at 13 08 25](https://user-images.githubusercontent.com/7490258/42033309-67fc0242-7ad4-11e8-8104-020f93ace3eb.png)
