### ISSUE TITLE
Finding help docs

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#50]
Eagle Genomics could not find our help pages.
They were looking at the opentargets.org rather than targetvalidation.org

On the same note: there is no direct link to the data_sources page from the homepage. And from the right hand side of https://targetvalidation.org/about#evidence we get a title that does not relate to me that easily (i.e. The evidence for target-disease associations). Data sources for target-disease associations may be more catchy, dunno.

**Comment by emepyc** [comment]
With the new redesign we have direct link to the data sources from the home page.
If something else needs to be done, please specify.
