### ISSUE TITLE
add NAR paper link to homepage

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#51]
It would be great to have a link to http://nar.oxfordjournals.org/content/early/2016/11/29/nar.gkw1055.abstract 

perhaps we could use the art cover?

**Comment by emepyc** [comment]
We already have a "how to cite us", isn't that enough?

**Comment by elipapa** [comment]
In my mind this is more to showcase the quality of the platform. I think
it's important to demonstrate that the way genes are ranked has been vetted
and considered impactful. This can inspire more trust from the casual
visitor and convert them to regular users? :fingers crossed:

On Wed, Jan 18, 2017 at 1:02 PM, Miguel Pignatelli <notifications@github.com

**Comment by emepyc** [comment]
A new section has been added now to the home page with a link to the nar paper.
