### ISSUE TITLE
fly genes don't come up in ortholog search

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#58]
These genes don't give search results:

dikar
east
Vha44
VhaAC45
CTPsyn
CTPsyn
AGO1
Fs(2)Ket
CG43319
CG43320
psq
DnaJ-1
Mocs1
vnc
Vha68-2
eIF-2gamma
Su(var)3-9
BubR1
tgo
Flo-2

**Comment by elipapa** [comment]
This issue was moved to opentargets/data_pipeline#52
