### ISSUE TITLE
Show name of targets not associated with the disease in the filter-by-target-list feature

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#61]
The problem with this feature is that the target list works as a facet in the sense that we only get the numbers back, but not the names of the targets associated vs not associated.

The associated ones are visible in the table itself (server-side paginated!).

**Comment by elipapa** [comment]
will wait for #71 metrics before deciding on fixing this.

**Comment by emepyc** [comment]
We can not get that information from the api with the current implementation.
