### ISSUE TITLE
Missing setup step in README

### ISSUE THREAD

**Issue by rbrunt** [opentargets/webapp#63]
The "Install" section of the README doesn't mention the need to run `npm run setup` to install bower and jspm packages before running a gulp build. I think this used to be run automatically as part of an npm "postinstall" hook.

The README also doesn't mention the dependency on jspm that was added last release.

**Comment by emepyc** [comment]
Regarding the new _setup_ step, you are right, this has changed and was not reflected in the documentation, I'll update the README.

The dependency on jspm is not new and I don't think it has to be mentioned though, it is installed as part of the `npm install` process and should be transparent.

**Comment by rbrunt** [comment]
I didn't have any issues with it being installed - it was just that it never got run since this commit: https://github.com/opentargets/webapp/commit/8823bd3ac95b73409e9cde6ebe238d68d68e2cb3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 - the `jspm install` command to install the dependencies managed by jspm was being called as part of the `post-install` hook, but it looks like that's been removed.

**Comment by emepyc** [comment]
Ah, ok. So it's just a matter of updating the documentation to reflect the need of running `npm run setup`

**Comment by emepyc** [comment]
This should be fixed now in 2.0.7
