### ISSUE TITLE
No exact matches in mapping page of batch search

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#64]
# Problem description

[While testing the first iteration of batch search](https://docs.google.com/document/d/1ZDPWqSHhw4Kl_cOqBkTTaWNOG5VikrOLapeA2NCGz5w/edit?usp=sharing) (pull request #16) we noticed that there were no exact matches in the results of the mapping. 

For example, instead of the following:
![02-mapping-01-screencapture-beta-targetvalidation-org-batch-search-1478265709460](https://cloud.githubusercontent.com/assets/20280139/21984571/725289d6-dbee-11e6-9033-b20286f3e96e.png)

All exact matches (e.g. PTGS2 -> PTGS2) were under “suggested matches”.  This is probably is due to some formatting that the participants' editor added when opening/saving our list of targets from their email.

@emepyc said that he has resolved this issue. We want to test it in the webapp to make sure it behaves as we expect (and to get more accurate feedback on the 3 categories of Mapping).

**Comment by nikiforosk** [comment]
@emepyc I wanted to flag this as a bug and assign it to you but can't figure out how to do that... Please do this when you have a sec!

**Comment by emepyc** [comment]
This is fixed now, although we still have several mapping bugs with genes having dashes in the rest api. See:
https://github.com/opentargets/rest_api/issues/52
