### ISSUE TITLE
When going back from the Summary page to the Mapping page, show the results of the mapping

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#65]
# What problem does this feature solve?

## Example use case

Towards the end of the first user feedback session of iteration 1 of batch search (pull request #16), [the participant went back from the Summary page to the Mapping page](https://docs.google.com/document/d/1enEr1SsNjTJfGSj4rJdlp4IzQw6AP0EpsHVdyeBEpdo/edit#bookmark=id.ne83mpmcpx52). The page looked empty:

![02-mapping-02-goingback-screencapture-beta-targetvalidation-org-batch-search-1478873349887](https://cloud.githubusercontent.com/assets/20280139/21985417/750be4fc-dbf2-11e6-98b7-61424abf542d.png)

To show the result of the mapping the participant had to click on the link under "Previously uploaded targets" (I don't think she noticed that). Instead she tried to upload her file again.

I think it will be helpful in these contexts to show the result of the last uploaded file, e.g. 
![02-mapping-01-screencapture-beta-targetvalidation-org-batch-search-1478265709460](https://cloud.githubusercontent.com/assets/20280139/21985463/b76d4214-dbf2-11e6-94ad-ebaf1b1b4751.png)
instead of a seemingly empty page.

@emepyc said that he has resolved this issue. We want to test it in the webapp to make sure it behaves as we expect.

**Comment by emepyc** [comment]
This particular issue is fixed.
