### ISSUE TITLE
Bar charts on Summary page of batch search not showing in IE11

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#66]
# What problem does this feature solve?

[While testing the first iteration of batch search](https://docs.google.com/document/d/1ZDPWqSHhw4Kl_cOqBkTTaWNOG5VikrOLapeA2NCGz5w/edit?usp=sharing) (pull request #16) with participants from GSK who were using IE11 (their officially supported browser), we noticed that the bar charts on the Summary page were not showing:

![03-summary-tas-immune-system-disease-screen shot 2016-11-11 at 12 12 37 2](https://cloud.githubusercontent.com/assets/20280139/21985787/4e2cdbc8-dbf4-11e6-8b48-9aff265e676e.png)

I think these appear in 3 places:
- Therapeutic areas (screenshot above)
- Disease table view (possibly ???)
- Pathways 

# Testing the fix

Check that the bars are showing in IE11. Could use the GSK vanilla laptop for this.

**Comment by emepyc** [comment]
I think this was fixed in the v02 of batch search. We can reopen if the issue appears again
