### ISSUE TITLE
Add error message for section which is not shown on Summary page

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#67]
# Problem description

While I was trying https://batch-search.targetvalidation.org/batch-search, in noticed that a couple of times the Summary page loaded (rather slowly) but didn’t show the Drugs section. 

I cannot replicate this reliably. However, @emepyc suggested that he could add an error message to inform the user that part of the page failed to load. 

We need to decide on the text for this message. How about:

"We cannot show the drugs that are associated with your list of targets. Please email support@targetvalidation.org to let us know of this error in order to try to fix it."

(But wouldn't it be better if the app itself let us know about the error and any relevant info? A bit like an automatic crash report?)

In general, it is recommended that we suggest an action for the user which can override the error. But I'm not sure what this action could be: "Please try again later" isn't a very helpful one :-)

# Testing the fix

Replicate the error (e.g. by switching off internet connection ???).
Check that error message is shown.
Ideally, show error message to participants and make sure they understand it (and even more ideally that they do whatever amending action we recommend).

**Comment by ElaineMcA** [comment]
Issue moved to [opentargets/platform #26](https://github.com/opentargets/platform/issues/26) via [**ZenHub**](https://www.zenhub.com/)
