### ISSUE TITLE
Remove “We have several targets ...” at the top of Summary page of batch search

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#68]
Remove “We have several targets: ["ENSG00000172057", ...” at the top of the Summary page of batch search:

![03-summary-drugs-01-open-screencapture-beta-targetvalidation-org-summary-1477666407352 copy](https://cloud.githubusercontent.com/assets/20280139/21990333/506c14be-dc06-11e6-8aa4-14c15dff9965.png)

**Comment by emepyc** [comment]
This was fixed already
