### ISSUE TITLE
Links missing on disease/target association page when no target/disease are associated

### ISSUE THREAD

**Issue by gkos-bio** [opentargets/webapp#70]
The link to the disease profile or the target profile pages are missing when no target/no disease are associated preventing users to navigate to the profile pages

**Comment by LucaFumis** [comment]
The line is styled/phrased differently, but appears to have a link at the end:

https://www.targetvalidation.org/target/ENSG00000240268/associations
> No diseases found for MOXD2P
> Find more information about MOXD2P in its Profile page

https://www.targetvalidation.org/disease/EFO_1000725/associations
> No targets found for lichen nitidus
> Find more information about lichen nitidus in its Profile page

**Comment by emepyc** [comment]
Yes, I fixed that some weeks ago but forgot to close this issue
