### ISSUE TITLE
residual 'Target Validation' name

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#74]
When posting a link in Slack e.g.
http://targetvalidation.org/evidence/ENSG00000140545/EFO_0005772

we get the 'old' Target Validation name of the Platform lingering still:

![screen shot 2017-01-27 at 11 18 07](https://cloud.githubusercontent.com/assets/6472381/22369450/d2dba8bc-e483-11e6-9c5d-3899722c0581.png)

The name also remains when clicking on the 'Feedback' button to send the email via an email client e.g.

![screen shot 2017-01-27 at 11 27 21](https://cloud.githubusercontent.com/assets/6472381/22369416/a6683318-e483-11e6-942c-da9b53820356.png)

**Comment by emepyc** [comment]
This is now fixed and deployed in 2.0.8
