### ISSUE TITLE
Clicking on the score link below the Bubbles should take you to score FAQ

### ISSUE THREAD

**Issue by nikiforosk** [opentargets/webapp#79]
Clicking on the Score link below the legend of the Bubbles (or the other two views) should take you directly to the score FAQ. Instead one often sees a page like this that doesn't show the score FAQ (especially on a laptop screen with a window that is not maximised):
<img width="1091" alt="faq-page-after-clicking-on-score-link-screen shot 2017-02-13 at 09 18 31" src="https://cloud.githubusercontent.com/assets/20280139/22899912/6a49062e-f224-11e6-98b5-70230fbf2a4f.png">

When people don't see the score FAQ on the top of the page, they get confused and often click Back. We noticed this several times in the feedback sessions of 2016, and more recently in [a session with Shila from Biogen](https://docs.google.com/document/d/1Xz_LHQKkyczd2_w5Rk4C6IPFYCTOPJ-NT2stNjwMUIA/edit#bookmark=id.qbvxg8xoivku):
"She clicks on the Score link under the bubbles view but doesn't see the FAQ for the score (she needed to scroll down to see it) so clicks Back"

@LucaFumis Is it possible to show the score FAQ on the top of the new page so that people don't have to scroll down to find it?

**Comment by LucaFumis** [comment]
Well spotted - it’s a broken link:
link points to /faq#association-score but the anchor on the page is called #score

L
