### ISSUE TITLE
create a search component for use in external sites

### ISSUE THREAD

**Issue by emepyc** [opentargets/webapp#82]
Requested by biogen

**Comment by LucaFumis** [comment]
I've been looking into possible implementations.
A search bar that clicks through to our results page would be/work OK
On the other hand, a drop down with search suggestions would be very challenging to implement.

2 possible approaches for an inline search box:
iframe (simple page with just the serachbox)
js script tag (call script that generates the html)

**Comment by emepyc** [comment]
@LucaFumis , there is also the option of creating a full js component (as the ones we currently have)

**Comment by LucaFumis** [comment]
Ah, that's right @emepyc . 
In that case they would have to download/install/add the component to their code (which is OK I guess), right?
I was thinking of a "just add one line/tag to the html" type of approach, to make it simpler for users to embed in their pages (I suppose it could still be done as component... just served via our server)

**Comment by emepyc** [comment]
No need to download & install if we have the final library available somewhere. For example, if we develop this component in a different repo, build it and make it available through github pages (as a CDN), you can just call it from any web page using a normal script tag.

You still need to instantiate it, but this can be 1 extra line of code in the host app.

**Comment by LucaFumis** [comment]
great! I didn't think of github pages :)
Otherwise seems a similar approach (making it available somewhere and called from user page)...

**Comment by elipapa** [comment]
What about something easy like this? @peatroot @LucaFumis 


```html
<html>
    <head></head>
    <body>
<form role="search" method="get" id="searchform" class="searchform" action="http://www.targetvalidation.org/search?src=q:">
  <div id="gform">
  <label class="screen-reader-text" for="s"></label>
  <input type="text" value="" name="q" id="s">
  <input type="submit" class="btn fa-input" value="&#xf002;" style="font-family: FontAwesome;">
</div>
</form>
</body>
```

**Comment by peatroot** [comment]
Yes, if you don't need the autocomplete, that'd work well. The styling would require font-awesome and bootstrap (the classes `fa-input` and `btn`). If the person integrating the widget has those or doesn't mind adding them, then should be fine. If they use a different styling library, they could get conflicts.

If they don't want to inject HTML directly, we could create a script (eg. `ot-search.js`) that adds this HTML on execution. That way, the user would just need to add `<script type="text/javascript" src="ot-search.js"></script>`.

It would be useful to know:
* Is the search going to be used only in one specific site environment?
* What styling library do they use?
* Do they use a framework? If so, which?

**Comment by elipapa** [comment]
Succesfully added in the sharepoint website:

![image](https://user-images.githubusercontent.com/112610/40554376-6dd1357c-603d-11e8-801a-384f9fba50a9.png)

Linking to this discussion from the FAQ, in case someone else asks. https://docs.targetvalidation.org/faq/what-can-i-search-for#embed-your-own-search-bar
