### ISSUE TITLE
showcase data release statistics separately from webapp improvements and API enhancements

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#84]
we should have some version of https://github.com/opentargets/data-providers-docs/wiki/Data-(Evidence-Strings)-Submission-Process#data-submission-statistics

included in the webapp downloads page

**Comment by emepyc** [comment]
a new stats page?

**Comment by elipapa** [comment]
are you referring to http://www.targetvalidation.org/release-notes ?

just like that. But we need to figure out if the release notes of the webapp are now decoupled from the ones of the data releases and how to announce the two streams in a coherent way. 

@deniseOme what do you think?

**Comment by emepyc** [comment]
Not sure I understand. A new data release means that the webapp will be serving that data, right? Why do you want to have a separated release notes?
Btw, I was not referring to the release notes, but a stats page that pulls data (stats endpoint of the rest api?) and displays useful information (what the homepage is doing now, but more detailed, maybe some graphics as well)

**Comment by elipapa** [comment]
related to https://github.com/opentargets/rest_api/issues/54
