### ISSUE TITLE
Make Table the default view of the associations page

### ISSUE THREAD

**Issue by emepyc** [opentargets/webapp#85]
@nikiforosk commented on [Wed Feb 08 2017](https://github.com/opentargets/features/issues/65)

Let's have an approximate A/B testing experiment by making the Table the default view of the associations page (perhaps in the Beta for a short period of time) to gather qualitative feedback and click metrics: will people switch from the Table to the Bubbles at same rate as they currently switch from Bubbles to the Table?

---

@emepyc commented on [Wed Feb 08 2017](https://github.com/opentargets/features/issues/65#issuecomment-278280276)

but regular users are not supposed to work on beta.

---

@elipapa commented on [Wed Feb 08 2017](https://github.com/opentargets/features/issues/65#issuecomment-278303153)

measure percentage of switches between tabs 3 days when production is at is and 3 days when we invert ;) ?

**Comment by andrewhercules** [comment]
Issue closed as it will be addressed in the upcoming 18.06/3.7 release of the Platform
