### ISSUE TITLE
Include a sentence/link to the NAR paper from the scoring page

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#89]
It may be worth linking from http://targetvalidation.org/scoring to the NAR paper.

If that's agreed, let me know and I can write a short paragraph.

**Comment by emepyc** [comment]
I'm happy to include this. It is included in 2.1.0 milestone so we can look at this in the following days.
If there is not agreement I'll remove it from the milestone

**Comment by emepyc** [comment]
The paragraph was added some time ago, so I'm closing this issue for now. If it needs revision, please feel free to reopen it.
