### ISSUE TITLE
Linking "Kafkas et al 2016" to the pdf

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#94]
In this page:
http://targetvalidation.org/scoring

We have the sentence: (Kafkas et al 2016)

Can we link it out to here:
https://opentargets.org/sites/default/files/documents/literature_evidence_in_cttv_-_a_target_validation_platform.pdf

Kafkas et al 2016 on its own is difficult to find on the web. It took me a little while. 
The original reference on the NAR paper does not seem to load/work anymore: http://phenoday2016.bio-lark.org

Besides, for animal models we do link out to the publication.

**Comment by emepyc** [comment]
I've now included the link, but I wonder how stable the link is
