### ISSUE TITLE
new FAQs for March release

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#96]
**What genome assembly is Open Targets using?**
We use GRCh38 (sometimes referred to as hg38). This is the latest human genome provided by the [Genome Reference Consortium](https://www.ncbi.nlm.nih.gov/grc). This is relevant when we display SNPs and other features on the genome. It also affects the set of targets that we use, which is based on the latest Ensembl version at the time of our release. However, because our focus is on evidence associating targets and diseases, we support most evidence data irrespective of the genome assembly that may have been used for their original analysis.

**How does Open Target assign variants (e.g. SNPs) to genes?**
We map and annotate variants to genes and transcripts using the Ensembl [Variant Effect Predictor](http://www.ensembl.org/info/docs/tools/vep/script/index.html). If a variant maps to a gene with different transcritps, we will assign it the most severe [variant definition](http://targetvalidation.org/variants) or consequence term (e.g. start loss, stop gained) from the Sequence Ontology (SO). If the variant maps to intergenic regions, we will assign the variant to the 5' end (i.e. nearest the likely promoter) of the closest protein coding gene on either strand (forward or reverse) within a 500 kb window.

**The Platform does not report a known association between gene A with disease B. Why isn’t this information in Open Targets?**
If we miss known associations that are described elsewhere, please [get in touch](mailto:support@targetvalidation.org). The reasons can be severalfold and we will look at the examples on a case-by-case basis. If the known association is described in a recent paper, it will not have made it through the curation process within our data sources yet. If the known association is based on a variant with an ID (e.g. rs123, His166Tyr), please include that information as well. We are revisiting our variant-to-gene assignment to assess if eQTLs could give a more likely assignment than the one in use, which is based on functional data only as described in "[How does Open Target assign variants (e.g. SNPs) to genes?](https://www.targetvalidation.org/faq#variants)". By providing this information, you can help us improve our analyses for variant-to-gene assignment.

**What is the difference between direct and non-direct associations for targets and diseases?** 
We take into account the ontology of diseases from Experimental Factor Ontology (EFO) to propagate evidence up to their parent terms. This allows us to compute new target-disease associations when there is no direct (known and observed) evidence for them. 

**Why does Open Targets use EFO instead of other disease ontology?**
These are the reasons for choosing the Experimental Factor Ontology:
* It is an application ontology, therefore it can incorporate parts (or the whole) of other ontologies, such as the rare disease ontology ORDO.
* It is able to bring in additional (not disease only) ontologies.
* It can easily accommodate our requests for new ontology terms in addition to updates and changes, as Open Targets and the EFO team collaborate closely.
* It is the ontology of controlled vocabulary used by the GWAS catalog and Expression Atlas. Therefore, no extra step was needed when incorporating those two data sources in our pipeline.

**What are clinical trials?**
Clinical trials are studies carried out in human volunteers over a period of 10-15 years to investigate the safety and/or efficacy of a medicine. The Food and Drug Administration (FDA) describes the following phases:
	
• Phase I to assess the drug's most frequent (and serious) adverse events, and how the drug is metabolised and excreted. The number of subjects (either healthy volunteers or people with the disease/condition) ranges from 20 to 100. Phase I takes several months.

• Phase II provides preliminary data on the biological activity of a drug.  Safety continues to be evaluated, and short-term adverse events studied. Up to 300 subjects (volunteers with the disease/condition) are studied. Phase II takes between several months to two years.

• Phase III continues assessing effectiveness and adverse reactions. It is carried out in 300-3,000 volunteers with the disease/condition from different human populations. Different dosages and the combination with other drugs can be assessed. Phase III takes between one to four years.
	
• Phase IV occurs once the FDA authorises a drug for marketing. Further information on drug's safety, efficacy, or/and optimal use will be assessed in pharmacovigilance. 
Some phase IV drugs (e.g. from [ClinicalTrials.gov](https://clinicaltrials.gov/)) may also be in postmarketing surveillance, and used for conditions different from the ones for which the drug has been been originally approved for.  Several thousands volunteers who have the disease/condition are studied.

This [FDA infographic](https://www.fda.gov/downloads/Drugs/ResourcesForYou/Consumers/UCM284393.pdf) gives a summary of the different phases in a clinical trial.

**Comment by ckongEbi** [comment]
@deniseOme , expand a bit, feel free to re-phrase. 

"We annotate and map variants to genes using the Ensembl Variant Effect Predictor. The variant will be assigned to the gene from protein coding transcript that has the most_severe_consequence. If it is an intragenic gene, we will assign the variant to the protein coding gene whose 5' end is closest (i.e. nearest the likely promoter) on either strand within a 500 kb window. "

**Comment by deniseOme** [comment]
I will add links to some of the words in these new FAQs such as Variant Effect Predictor, etc.

**Comment by deniseOme** [comment]
6 new FAQs in total. Links inserted. If the last FAQ (clinical trials) is too long, we may be able to shortened it somehow...

**Comment by deniseOme** [comment]
Please check the google docs for some subtle changes on the existing FAQs:

https://docs.google.com/document/d/1IyyN33EkwKG1QuJBvLUamBvSV2orYleKCG4CO19xJug/edit?usp=sharing

Not sure about the order of the FAQs...We can look at a beta version...
