### ISSUE TITLE
search inconsistencies

### ISSUE THREAD

**Issue by deniseOme** [opentargets/webapp#98]
while searching for Spinocerebellar ataxia type 1 gives no results whether in production or beta:

https://beta.opentargets.io/search?src=q:Spinocerebellar%20ataxia%20type%201

http://www.targetvalidation.org/search?src=q:Spinocerebellar%20ataxia%20type%201

searching for the orphanet ID it does work though:
http://www.targetvalidation.org/search?src=q:Orphanet_98755

searching for Spinocerebellar ataxia type seems to give results:
http://www.targetvalidation.org/search?src=q:Spinocerebellar%20ataxia%20type

Is this related to
https://github.com/opentargets/rest_api/issues/38
?

**Comment by emepyc** [comment]
Issue moved to [opentargets/rest_api #64](https://github.com/opentargets/rest_api/issues/64) via [**ZenHub**](https://www.zenhub.com/)
